// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AgentMemory struct {
	ID        int64              `json:"id"`
	Scope     string             `json:"scope"`
	ScopeID   int64              `json:"scopeId"`
	GuildID   int64              `json:"guildId"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type AgentMemoryDigest struct {
	ID              int16              `json:"id"`
	LastRunAt       pgtype.Timestamptz `json:"lastRunAt"`
	Watermark       pgtype.Timestamptz `json:"watermark"`
	MessagesSeen    int32              `json:"messagesSeen"`
	MemoriesWritten int32              `json:"memoriesWritten"`
}

type AnniversaryPost struct {
	GuildID   int64              `json:"guildId"`
	LocalDate pgtype.Date        `json:"localDate"`
	SongCount int32              `json:"songCount"`
	PostedAt  pgtype.Timestamptz `json:"postedAt"`
}

type Background struct {
	ID         int64              `json:"id"`
	Filename   string             `json:"filename"`
	UploadedBy pgtype.Int8        `json:"uploadedBy"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
}

type Guild struct {
	GuildID                         int64       `json:"guildId"`
	ModlogsChannel                  pgtype.Int8 `json:"modlogsChannel"`
	LeaveJoinLogsChannel            pgtype.Int8 `json:"leaveJoinLogsChannel"`
	YoutubeNotificationsChannel     pgtype.Int8 `json:"youtubeNotificationsChannel"`
	YoutubeNotificationsRole        pgtype.Int8 `json:"youtubeNotificationsRole"`
	RedditNotificationsChannel      pgtype.Int8 `json:"redditNotificationsChannel"`
	RedditNotificationsRole         pgtype.Int8 `json:"redditNotificationsRole"`
	StmpdNotificationsChannel       pgtype.Int8 `json:"stmpdNotificationsChannel"`
	StmpdNotificationsRole          pgtype.Int8 `json:"stmpdNotificationsRole"`
	WelcomesChannel                 pgtype.Int8 `json:"welcomesChannel"`
	DeleteLogsChannel               pgtype.Int8 `json:"deleteLogsChannel"`
	EditLogsChannel                 pgtype.Int8 `json:"editLogsChannel"`
	BotChannel                      pgtype.Int8 `json:"botChannel"`
	RadioVoiceChannel               pgtype.Int8 `json:"radioVoiceChannel"`
	NewsRole                        pgtype.Int8 `json:"newsRole"`
	XpMultiplier                    float64     `json:"xpMultiplier"`
	TourNotificationsChannel        pgtype.Int8 `json:"tourNotificationsChannel"`
	TourNotificationsRole           pgtype.Int8 `json:"tourNotificationsRole"`
	ModeratorRole                   pgtype.Int8 `json:"moderatorRole"`
	AnniversaryNotificationsChannel pgtype.Int8 `json:"anniversaryNotificationsChannel"`
	AnniversaryNotificationsRole    pgtype.Int8 `json:"anniversaryNotificationsRole"`
	AnniversaryHour                 int32       `json:"anniversaryHour"`
	AnniversaryTimezone             string      `json:"anniversaryTimezone"`
	VoiceLogsChannel                pgtype.Int8 `json:"voiceLogsChannel"`
	MemberLogsChannel               pgtype.Int8 `json:"memberLogsChannel"`
	LevelUpRole                     pgtype.Int8 `json:"levelUpRole"`
	LevelUpRoleLevel                int32       `json:"levelUpRoleLevel"`
	BackgroundMode                  string      `json:"backgroundMode"`
	BackgroundCycleBackgroundID     pgtype.Int8 `json:"backgroundCycleBackgroundId"`
	SingAlongChannel                pgtype.Int8 `json:"singAlongChannel"`
	SingAlongHour                   int32       `json:"singAlongHour"`
	SingAlongTimezone               string      `json:"singAlongTimezone"`
	SingAlongCooldownMinutes        int32       `json:"singAlongCooldownMinutes"`
}

type GuildBackground struct {
	GuildID      int64 `json:"guildId"`
	BackgroundID int64 `json:"backgroundId"`
}

type JoinLeaveLog struct {
	MemberID int64            `json:"memberId"`
	Action   string           `json:"action"`
	Time     pgtype.Timestamp `json:"time"`
	ID       int64            `json:"id"`
	GuildID  int64            `json:"guildId"`
}

type Message struct {
	MessageID     int64            `json:"messageId"`
	ChannelID     int64            `json:"channelId"`
	AuthorID      pgtype.Int8      `json:"authorId"`
	Content       string           `json:"content"`
	Timestamp     pgtype.Timestamp `json:"timestamp"`
	GuildID       int64            `json:"guildId"`
	AuthorGuildID int64            `json:"authorGuildId"`
}

type Modlog struct {
	ID          int64            `json:"id"`
	UserID      int64            `json:"userId"`
	ModeratorID int64            `json:"moderatorId"`
	LogType     string           `json:"logType"`
	Reason      pgtype.Text      `json:"reason"`
	Time        pgtype.Timestamp `json:"time"`
	GuildID     int64            `json:"guildId"`
	ExpiresAt   pgtype.Timestamp `json:"expiresAt"`
	Active      pgtype.Bool      `json:"active"`
	AuditLogID  pgtype.Int8      `json:"auditLogId"`
}

type RedditPost struct {
	PostID string `json:"postId"`
}

type SingAlongRound struct {
	GuildID     int64              `json:"guildId"`
	LocalDate   pgtype.Date        `json:"localDate"`
	SongID      pgtype.Int8        `json:"songId"`
	LyricLines  []string           `json:"lyricLines"`
	Cursor      int32              `json:"cursor"`
	StartedAt   pgtype.Timestamptz `json:"startedAt"`
	CompletedAt pgtype.Timestamptz `json:"completedAt"`
}

type Song struct {
	ID                int64              `json:"id"`
	Name              string             `json:"name"`
	Artists           string             `json:"artists"`
	ThumbnailUrl      pgtype.Text        `json:"thumbnailUrl"`
	SpotifyUrl        pgtype.Text        `json:"spotifyUrl"`
	AppleMusicUrl     pgtype.Text        `json:"appleMusicUrl"`
	YoutubeUrl        pgtype.Text        `json:"youtubeUrl"`
	Lyrics            pgtype.Text        `json:"lyrics"`
	IsUnreleased      bool               `json:"isUnreleased"`
	BeatportID        pgtype.Int4        `json:"beatportId"`
	MixName           pgtype.Text        `json:"mixName"`
	ReleaseDate       pgtype.Text        `json:"releaseDate"`
	ReleaseName       pgtype.Text        `json:"releaseName"`
	Genre             pgtype.Text        `json:"genre"`
	SubGenre          pgtype.Text        `json:"subGenre"`
	Bpm               pgtype.Int4        `json:"bpm"`
	MusicalKey        pgtype.Text        `json:"musicalKey"`
	LengthMs          pgtype.Int4        `json:"lengthMs"`
	BeatportUpdated   bool               `json:"beatportUpdated"`
	Source            string             `json:"source"`
	FirstSeenAt       pgtype.Timestamptz `json:"firstSeenAt"`
	AnnouncedAt       pgtype.Timestamptz `json:"announcedAt"`
	StmpdSyncedAt     pgtype.Timestamptz `json:"stmpdSyncedAt"`
	DeezerUrl         pgtype.Text        `json:"deezerUrl"`
	TidalUrl          pgtype.Text        `json:"tidalUrl"`
	AmazonMusicUrl    pgtype.Text        `json:"amazonMusicUrl"`
	YoutubeMusicUrl   pgtype.Text        `json:"youtubeMusicUrl"`
	BeatportUrl       pgtype.Text        `json:"beatportUrl"`
	BeatportReleaseID pgtype.Int4        `json:"beatportReleaseId"`
	StmpdSlug         pgtype.Text        `json:"stmpdSlug"`
	MatchKey          pgtype.Text        `json:"matchKey"`
	BaseKey           pgtype.Text        `json:"baseKey"`
	ParentSongID      pgtype.Int8        `json:"parentSongId"`
	IsInstrumental    bool               `json:"isInstrumental"`
	IsCollection      bool               `json:"isCollection"`
	BeatportSlug      pgtype.Text        `json:"beatportSlug"`
	NormalizedName    pgtype.Text        `json:"normalizedName"`
	LrclibID          pgtype.Int8        `json:"lrclibId"`
	LrclibCheckedAt   pgtype.Timestamptz `json:"lrclibCheckedAt"`
	LrclibMisses      int16              `json:"lrclibMisses"`
	LockedFields      []string           `json:"lockedFields"`
	SearchText        pgtype.Text        `json:"searchText"`
}

type SongAnnouncement struct {
	SongID     int64              `json:"songId"`
	GuildID    int64              `json:"guildId"`
	ChannelID  int64              `json:"channelId"`
	MessageID  int64              `json:"messageId"`
	ButtonsKey string             `json:"buttonsKey"`
	PostedAt   pgtype.Timestamptz `json:"postedAt"`
	EditedAt   pgtype.Timestamptz `json:"editedAt"`
	EditCount  int16              `json:"editCount"`
	FailedAt   pgtype.Timestamptz `json:"failedAt"`
}

type Tag struct {
	CreatorID int64            `json:"creatorId"`
	Content   string           `json:"content"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	Uses      pgtype.Int4      `json:"uses"`
	Name      string           `json:"name"`
}

type TourShow struct {
	ID        int64            `json:"id"`
	ShowName  string           `json:"showName"`
	City      string           `json:"city"`
	Country   string           `json:"country"`
	Venue     string           `json:"venue"`
	ShowDate  pgtype.Date      `json:"showDate"`
	TicketUrl pgtype.Text      `json:"ticketUrl"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

type User struct {
	ID           int64            `json:"id"`
	MessagesSent int32            `json:"messagesSent"`
	TotalXp      int32            `json:"totalXp"`
	LastXpAdded  pgtype.Timestamp `json:"lastXpAdded"`
	StmpdCoins   int64            `json:"stmpdCoins"`
	InHand       int64            `json:"inHand"`
	GuildID      int64            `json:"guildId"`
}

type YoutubeVideo struct {
	VideoID string `json:"videoId"`
}
