// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sing_along.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceSingAlongCursor = `-- name: AdvanceSingAlongCursor :execrows
UPDATE sing_along_rounds
   SET cursor = cursor + 1
 WHERE guild_id = $1 AND cursor = $2 AND completed_at IS NULL
`

type AdvanceSingAlongCursorParams struct {
	GuildID int64 `json:"guildId"`
	Cursor  int32 `json:"cursor"`
}

// Advances the round by one line. Returns 1 when this member's guess won the line
// and 0 when someone else got there first.
//
// The cursor is matched, not just incremented, so two correct guesses arriving in
// the same instant cannot both be paid: the second finds the cursor already moved
// and updates nothing. The in-memory round does the same compare-and-swap first;
// this is what actually decides, because it is the only copy two bot instances
// share.
func (q *Queries) AdvanceSingAlongCursor(ctx context.Context, arg AdvanceSingAlongCursorParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceSingAlongCursor, arg.GuildID, arg.Cursor)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimSingAlongDay = `-- name: ClaimSingAlongDay :execrows
INSERT INTO sing_along_rounds (guild_id, local_date, song_id, lyric_lines)
VALUES ($1, $2, $3, $4)
ON CONFLICT (guild_id) DO UPDATE
   SET local_date   = EXCLUDED.local_date,
       song_id      = EXCLUDED.song_id,
       lyric_lines  = EXCLUDED.lyric_lines,
       cursor       = 1,
       started_at   = NOW(),
       completed_at = NULL
 WHERE sing_along_rounds.local_date IS DISTINCT FROM EXCLUDED.local_date
   AND sing_along_rounds.started_at < NOW() - INTERVAL '12 hours'
`

type ClaimSingAlongDayParams struct {
	GuildID    int64       `json:"guildId"`
	LocalDate  pgtype.Date `json:"localDate"`
	SongID     pgtype.Int8 `json:"songId"`
	LyricLines []string    `json:"lyricLines"`
}

// Claims a guild's round for one local day, atomically. Returns 1 when this caller
// won the claim and must wipe the channel and post, 0 when the day was already
// taken.
//
// The upsert is the claim, so two ticks racing each other -- or two bot instances --
// cannot both wipe a channel. The WHERE on the DO UPDATE is what makes it a claim
// rather than a blind overwrite: a round already rolled for today, part-way through
// its song, is left exactly as it is.
//
// Claimed before the wipe, not after, for the same reason as ClaimAnniversaryDay: a
// crash mid-send costs one day's lyric, while claiming afterwards would re-wipe the
// channel on the next tick, and of the two, quiet is the safer failure.
//
// IS DISTINCT FROM rather than "<", because a guild moved westward -- Auckland to
// Los Angeles -- has its local date go BACKWARD by a day, and a "<" test would leave
// the round unclaimable until the calendar caught up. The twelve hour floor on
// started_at is what keeps that same looseness from re-wiping a channel an hour
// after a timezone edit; the re-roll button is the escape hatch for anything this
// refuses.
func (q *Queries) ClaimSingAlongDay(ctx context.Context, arg ClaimSingAlongDayParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimSingAlongDay,
		arg.GuildID,
		arg.LocalDate,
		arg.SongID,
		arg.LyricLines,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeSingAlongRound = `-- name: CompleteSingAlongRound :exec
UPDATE sing_along_rounds SET completed_at = NOW() WHERE guild_id = $1
`

func (q *Queries) CompleteSingAlongRound(ctx context.Context, guildID int64) error {
	_, err := q.db.Exec(ctx, completeSingAlongRound, guildID)
	return err
}

const deleteSingAlongRound = `-- name: DeleteSingAlongRound :exec
DELETE FROM sing_along_rounds WHERE guild_id = $1
`

func (q *Queries) DeleteSingAlongRound(ctx context.Context, guildID int64) error {
	_, err := q.db.Exec(ctx, deleteSingAlongRound, guildID)
	return err
}

const getSingAlongGuilds = `-- name: GetSingAlongGuilds :many
SELECT guild_id,
       sing_along_channel,
       sing_along_hour,
       sing_along_timezone,
       sing_along_cooldown_minutes
FROM guilds
WHERE sing_along_channel IS NOT NULL
`

type GetSingAlongGuildsRow struct {
	GuildID                  int64       `json:"guildId"`
	SingAlongChannel         pgtype.Int8 `json:"singAlongChannel"`
	SingAlongHour            int32       `json:"singAlongHour"`
	SingAlongTimezone        string      `json:"singAlongTimezone"`
	SingAlongCooldownMinutes int32       `json:"singAlongCooldownMinutes"`
}

// Every guild with the feature switched on. Like GetAnniversaryGuilds this carries
// the schedule and the cooldown alongside the channel, because the scheduler needs
// all of them and none of the shared Get*NotificationChannels shapes fit.
func (q *Queries) GetSingAlongGuilds(ctx context.Context) ([]GetSingAlongGuildsRow, error) {
	rows, err := q.db.Query(ctx, getSingAlongGuilds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSingAlongGuildsRow
	for rows.Next() {
		var i GetSingAlongGuildsRow
		if err := rows.Scan(
			&i.GuildID,
			&i.SingAlongChannel,
			&i.SingAlongHour,
			&i.SingAlongTimezone,
			&i.SingAlongCooldownMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSingAlongRound = `-- name: GetSingAlongRound :one
SELECT guild_id, local_date, song_id, lyric_lines, cursor, started_at, completed_at FROM sing_along_rounds WHERE guild_id = $1
`

func (q *Queries) GetSingAlongRound(ctx context.Context, guildID int64) (SingAlongRound, error) {
	row := q.db.QueryRow(ctx, getSingAlongRound, guildID)
	var i SingAlongRound
	err := row.Scan(
		&i.GuildID,
		&i.LocalDate,
		&i.SongID,
		&i.LyricLines,
		&i.Cursor,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const replaceSingAlongRound = `-- name: ReplaceSingAlongRound :exec
INSERT INTO sing_along_rounds (guild_id, local_date, song_id, lyric_lines)
VALUES ($1, $2, $3, $4)
ON CONFLICT (guild_id) DO UPDATE
   SET local_date   = EXCLUDED.local_date,
       song_id      = EXCLUDED.song_id,
       lyric_lines  = EXCLUDED.lyric_lines,
       cursor       = 1,
       started_at   = NOW(),
       completed_at = NULL
`

type ReplaceSingAlongRoundParams struct {
	GuildID    int64       `json:"guildId"`
	LocalDate  pgtype.Date `json:"localDate"`
	SongID     pgtype.Int8 `json:"songId"`
	LyricLines []string    `json:"lyricLines"`
}

// The same upsert without the date guard, for a re-roll asked for by hand. An admin
// pressing the button has already said they want today's round replaced.
func (q *Queries) ReplaceSingAlongRound(ctx context.Context, arg ReplaceSingAlongRoundParams) error {
	_, err := q.db.Exec(ctx, replaceSingAlongRound,
		arg.GuildID,
		arg.LocalDate,
		arg.SongID,
		arg.LyricLines,
	)
	return err
}

const setSingAlongChannel = `-- name: SetSingAlongChannel :exec
UPDATE guilds SET sing_along_channel = $2 WHERE guild_id = $1
`

type SetSingAlongChannelParams struct {
	GuildID          int64       `json:"guildId"`
	SingAlongChannel pgtype.Int8 `json:"singAlongChannel"`
}

func (q *Queries) SetSingAlongChannel(ctx context.Context, arg SetSingAlongChannelParams) error {
	_, err := q.db.Exec(ctx, setSingAlongChannel, arg.GuildID, arg.SingAlongChannel)
	return err
}

const setSingAlongSchedule = `-- name: SetSingAlongSchedule :exec
UPDATE guilds
SET sing_along_hour = $2, sing_along_timezone = $3, sing_along_cooldown_minutes = $4
WHERE guild_id = $1
`

type SetSingAlongScheduleParams struct {
	GuildID                  int64  `json:"guildId"`
	SingAlongHour            int32  `json:"singAlongHour"`
	SingAlongTimezone        string `json:"singAlongTimezone"`
	SingAlongCooldownMinutes int32  `json:"singAlongCooldownMinutes"`
}

func (q *Queries) SetSingAlongSchedule(ctx context.Context, arg SetSingAlongScheduleParams) error {
	_, err := q.db.Exec(ctx, setSingAlongSchedule,
		arg.GuildID,
		arg.SingAlongHour,
		arg.SingAlongTimezone,
		arg.SingAlongCooldownMinutes,
	)
	return err
}
