// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: songs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adoptSongIdentifiers = `-- name: AdoptSongIdentifiers :exec
UPDATE songs SET
    beatport_id = COALESCE(beatport_id, $1),
    stmpd_slug  = COALESCE(stmpd_slug,  $2)
WHERE id = $3
`

type AdoptSongIdentifiersParams struct {
	BeatportID pgtype.Int4 `json:"beatportId"`
	StmpdSlug  pgtype.Text `json:"stmpdSlug"`
	ID         int64       `json:"id"`
}

// Give the surviving row the identifiers released above, without overwriting any it
// already has of its own.
func (q *Queries) AdoptSongIdentifiers(ctx context.Context, arg AdoptSongIdentifiersParams) error {
	_, err := q.db.Exec(ctx, adoptSongIdentifiers, arg.BeatportID, arg.StmpdSlug, arg.ID)
	return err
}

const clearPlaylistSpotifyLinks = `-- name: ClearPlaylistSpotifyLinks :execrows
UPDATE songs SET spotify_url = NULL WHERE spotify_url LIKE '%/playlist/%'
`

// Spotify playlist links cannot be resolved without the Spotify API, and pointing a
// song's Spotify button at a playlist is worse than showing no button.
func (q *Queries) ClearPlaylistSpotifyLinks(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, clearPlaylistSpotifyLinks)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearSongArtwork = `-- name: ClearSongArtwork :execrows
UPDATE songs SET thumbnail_url = NULL
WHERE id = $1
  AND thumbnail_url IS NOT NULL
  AND NOT ('thumbnail_url' = ANY(locked_fields))
`

// Removes a cover that belongs to a different song, so that the Apple enrichment can
// resolve the right one on its next pass.
//
// SetSongArtwork cannot do this: it is guarded on the column being empty, because its
// job is filling an absence and it must never overwrite what is already there. This one
// exists precisely to overwrite -- but only a value no human has claimed.
func (q *Queries) ClearSongArtwork(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, clearSongArtwork, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearStmpdSlug = `-- name: ClearStmpdSlug :execrows
UPDATE songs SET stmpd_slug = NULL WHERE id = $1
`

// Detach a release identity from a row it does not belong to.
func (q *Queries) ClearStmpdSlug(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, clearStmpdSlug, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearUnresolvedYoutubePlaylists = `-- name: ClearUnresolvedYoutubePlaylists :execrows
UPDATE songs SET youtube_url = NULL
WHERE youtube_url IS NOT NULL
  AND youtube_url NOT LIKE '%watch?v=%'
  AND youtube_url NOT LIKE '%youtu.be/%'
`

// A YouTube link that names a playlist rather than a video buys nothing: the radio
// ignores it and falls back to a search either way, and the button sends a listener
// to a playlist they did not ask for. Once everything resolvable has been resolved,
// what is left is better as no button at all.
func (q *Queries) ClearUnresolvedYoutubePlaylists(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, clearUnresolvedYoutubePlaylists)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const copyLyricsToRemixes = `-- name: CopyLyricsToRemixes :execrows
UPDATE songs t SET lyrics = s.lyrics, lrclib_id = s.lrclib_id
FROM songs s
WHERE s.id = $1 AND t.parent_song_id = s.id AND t.lyrics IS NULL
  AND s.lyrics IS NOT NULL AND NOT t.is_instrumental
`

// Lyrics are entered by hand against the canonical row. A remix of a vocal track has
// the same words, so fan them out rather than making someone paste them ten times.
//
// lrclib_id travels with the words, and must. It is what separates lyrics that came
// from LRCLIB from lyrics that exist nowhere else, and two things read that
// distinction: an automatic fill is reversible only if every row it wrote can be
// found, and dedupe-songs ranks a row carrying hand-entered lyrics above one without
// when it picks which duplicate survives. Copying the words but not their provenance
// made every fanned-out remix look hand-entered -- 146 of them on the first
// production run.
//
// A parent whose lyrics really were typed in has a NULL id, and the copy inherits
// that, which is correct: it is a copy of something irreplaceable.
func (q *Queries) CopyLyricsToRemixes(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, copyLyricsToRemixes, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countLinklessSongs = `-- name: CountLinklessSongs :one
SELECT count(*) FROM songs
WHERE spotify_url IS NULL AND apple_music_url IS NULL AND youtube_url IS NULL
`

func (q *Queries) CountLinklessSongs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLinklessSongs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSong = `-- name: DeleteSong :exec
DELETE FROM songs WHERE id = $1
`

func (q *Queries) DeleteSong(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSong, id)
	return err
}

const doesBeatportSongExist = `-- name: DoesBeatportSongExist :one
SELECT EXISTS(SELECT 1 FROM songs WHERE beatport_id = $1)
`

func (q *Queries) DoesBeatportSongExist(ctx context.Context, beatportID pgtype.Int4) (bool, error) {
	row := q.db.QueryRow(ctx, doesBeatportSongExist, beatportID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const doesSongExist = `-- name: DoesSongExist :one
SELECT EXISTS(SELECT 1 FROM songs
  WHERE name = $1 AND artists = $2 AND release_date IS NOT DISTINCT FROM $3)
`

type DoesSongExistParams struct {
	Name        string      `json:"name"`
	Artists     string      `json:"artists"`
	ReleaseDate pgtype.Text `json:"releaseDate"`
}

func (q *Queries) DoesSongExist(ctx context.Context, arg DoesSongExistParams) (bool, error) {
	row := q.db.QueryRow(ctx, doesSongExist, arg.Name, arg.Artists, arg.ReleaseDate)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getAllSongsForMatching = `-- name: GetAllSongsForMatching :many
SELECT id, name, artists, source, beatport_id, beatport_release_id,
       stmpd_slug, match_key, base_key, mix_name, spotify_url, stmpd_synced_at
FROM songs
`

type GetAllSongsForMatchingRow struct {
	ID                int64              `json:"id"`
	Name              string             `json:"name"`
	Artists           string             `json:"artists"`
	Source            string             `json:"source"`
	BeatportID        pgtype.Int4        `json:"beatportId"`
	BeatportReleaseID pgtype.Int4        `json:"beatportReleaseId"`
	StmpdSlug         pgtype.Text        `json:"stmpdSlug"`
	MatchKey          pgtype.Text        `json:"matchKey"`
	BaseKey           pgtype.Text        `json:"baseKey"`
	MixName           pgtype.Text        `json:"mixName"`
	SpotifyUrl        pgtype.Text        `json:"spotifyUrl"`
	StmpdSyncedAt     pgtype.Timestamptz `json:"stmpdSyncedAt"`
}

func (q *Queries) GetAllSongsForMatching(ctx context.Context) ([]GetAllSongsForMatchingRow, error) {
	rows, err := q.db.Query(ctx, getAllSongsForMatching)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllSongsForMatchingRow
	for rows.Next() {
		var i GetAllSongsForMatchingRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.Source,
			&i.BeatportID,
			&i.BeatportReleaseID,
			&i.StmpdSlug,
			&i.MatchKey,
			&i.BaseKey,
			&i.MixName,
			&i.SpotifyUrl,
			&i.StmpdSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCanonicalSongsForReview = `-- name: GetCanonicalSongsForReview :many
SELECT id, name, artists, release_date, source, base_key, match_key,
       spotify_url, youtube_url, apple_music_url, beatport_id
FROM songs WHERE parent_song_id IS NULL AND base_key IS NOT NULL AND base_key <> '|'
ORDER BY base_key, id
`

type GetCanonicalSongsForReviewRow struct {
	ID            int64       `json:"id"`
	Name          string      `json:"name"`
	Artists       string      `json:"artists"`
	ReleaseDate   pgtype.Text `json:"releaseDate"`
	Source        string      `json:"source"`
	BaseKey       pgtype.Text `json:"baseKey"`
	MatchKey      pgtype.Text `json:"matchKey"`
	SpotifyUrl    pgtype.Text `json:"spotifyUrl"`
	YoutubeUrl    pgtype.Text `json:"youtubeUrl"`
	AppleMusicUrl pgtype.Text `json:"appleMusicUrl"`
	BeatportID    pgtype.Int4 `json:"beatportId"`
}

// Songs as a user sees them, for reporting likely-duplicate groups that are not safe
// to merge automatically.
func (q *Queries) GetCanonicalSongsForReview(ctx context.Context) ([]GetCanonicalSongsForReviewRow, error) {
	rows, err := q.db.Query(ctx, getCanonicalSongsForReview)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCanonicalSongsForReviewRow
	for rows.Next() {
		var i GetCanonicalSongsForReviewRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.ReleaseDate,
			&i.Source,
			&i.BaseKey,
			&i.MatchKey,
			&i.SpotifyUrl,
			&i.YoutubeUrl,
			&i.AppleMusicUrl,
			&i.BeatportID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDuplicateMatchKeyRows = `-- name: GetDuplicateMatchKeyRows :many
SELECT id, name, artists, mix_name, release_date, source, match_key,
       stmpd_slug, beatport_id, spotify_url, apple_music_url, youtube_url,
       lyrics, parent_song_id, thumbnail_url
FROM songs
WHERE match_key IN (
    SELECT match_key FROM songs
    WHERE match_key IS NOT NULL AND match_key <> '||'
    GROUP BY match_key HAVING count(*) > 1
)
ORDER BY match_key, id
`

type GetDuplicateMatchKeyRowsRow struct {
	ID            int64       `json:"id"`
	Name          string      `json:"name"`
	Artists       string      `json:"artists"`
	MixName       pgtype.Text `json:"mixName"`
	ReleaseDate   pgtype.Text `json:"releaseDate"`
	Source        string      `json:"source"`
	MatchKey      pgtype.Text `json:"matchKey"`
	StmpdSlug     pgtype.Text `json:"stmpdSlug"`
	BeatportID    pgtype.Int4 `json:"beatportId"`
	SpotifyUrl    pgtype.Text `json:"spotifyUrl"`
	AppleMusicUrl pgtype.Text `json:"appleMusicUrl"`
	YoutubeUrl    pgtype.Text `json:"youtubeUrl"`
	Lyrics        pgtype.Text `json:"lyrics"`
	ParentSongID  pgtype.Int8 `json:"parentSongId"`
	ThumbnailUrl  pgtype.Text `json:"thumbnailUrl"`
}

// Every row belonging to a match_key held by more than one row. A match_key is the
// artist set, the base title and the rendition, so two rows sharing one are the same
// recording stored twice -- usually once per source, with the variant in `name` on
// one side and in `mix_name` on the other.
func (q *Queries) GetDuplicateMatchKeyRows(ctx context.Context) ([]GetDuplicateMatchKeyRowsRow, error) {
	rows, err := q.db.Query(ctx, getDuplicateMatchKeyRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDuplicateMatchKeyRowsRow
	for rows.Next() {
		var i GetDuplicateMatchKeyRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.MixName,
			&i.ReleaseDate,
			&i.Source,
			&i.MatchKey,
			&i.StmpdSlug,
			&i.BeatportID,
			&i.SpotifyUrl,
			&i.AppleMusicUrl,
			&i.YoutubeUrl,
			&i.Lyrics,
			&i.ParentSongID,
			&i.ThumbnailUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRandomSongForRadio = `-- name: GetRandomSongForRadio :one
SELECT id, name, artists, thumbnail_url, youtube_url
FROM songs
WHERE youtube_url IS NOT NULL
  AND parent_song_id IS NULL
  AND NOT is_collection
  AND (length_ms IS NULL OR length_ms <= 600000)
ORDER BY RANDOM()
LIMIT 1
`

type GetRandomSongForRadioRow struct {
	ID           int64       `json:"id"`
	Name         string      `json:"name"`
	Artists      string      `json:"artists"`
	ThumbnailUrl pgtype.Text `json:"thumbnailUrl"`
	YoutubeUrl   pgtype.Text `json:"youtubeUrl"`
}

// Canonical rows only, so the rotation does not play six versions of one track, and
// no collections: an EP, an album or a remix package is a release containing songs,
// not a song, and queueing one asks the player to stream a whole record as a track.
func (q *Queries) GetRandomSongForRadio(ctx context.Context) (GetRandomSongForRadioRow, error) {
	row := q.db.QueryRow(ctx, getRandomSongForRadio)
	var i GetRandomSongForRadioRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Artists,
		&i.ThumbnailUrl,
		&i.YoutubeUrl,
	)
	return i, err
}

const getRandomSongNames = `-- name: GetRandomSongNames :many
SELECT id, name, artists, mix_name, release_date
FROM songs
WHERE NOT is_collection AND parent_song_id IS NULL
ORDER BY RANDOM()
LIMIT 20
`

type GetRandomSongNamesRow struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	Artists     string      `json:"artists"`
	MixName     pgtype.Text `json:"mixName"`
	ReleaseDate pgtype.Text `json:"releaseDate"`
}

func (q *Queries) GetRandomSongNames(ctx context.Context) ([]GetRandomSongNamesRow, error) {
	rows, err := q.db.Query(ctx, getRandomSongNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRandomSongNamesRow
	for rows.Next() {
		var i GetRandomSongNamesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.MixName,
			&i.ReleaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRandomSongNamesWithLyrics = `-- name: GetRandomSongNamesWithLyrics :many
SELECT id, name, artists, mix_name, release_date
FROM songs
WHERE lyrics IS NOT NULL AND NOT is_collection AND parent_song_id IS NULL
ORDER BY RANDOM()
LIMIT 20
`

type GetRandomSongNamesWithLyricsRow struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	Artists     string      `json:"artists"`
	MixName     pgtype.Text `json:"mixName"`
	ReleaseDate pgtype.Text `json:"releaseDate"`
}

func (q *Queries) GetRandomSongNamesWithLyrics(ctx context.Context) ([]GetRandomSongNamesWithLyricsRow, error) {
	rows, err := q.db.Query(ctx, getRandomSongNamesWithLyrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRandomSongNamesWithLyricsRow
	for rows.Next() {
		var i GetRandomSongNamesWithLyricsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.MixName,
			&i.ReleaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRandomSongWithLyrics = `-- name: GetRandomSongWithLyrics :one
SELECT id, name, artists, thumbnail_url, spotify_url, apple_music_url, youtube_url, lyrics, is_unreleased, beatport_id, mix_name, release_date, release_name, genre, sub_genre, bpm, musical_key, length_ms, beatport_updated, source, first_seen_at, announced_at, stmpd_synced_at, deezer_url, tidal_url, amazon_music_url, youtube_music_url, beatport_url, beatport_release_id, stmpd_slug, match_key, base_key, parent_song_id, is_instrumental, is_collection, beatport_slug, normalized_name, lrclib_id, lrclib_checked_at, lrclib_misses, locked_fields, search_text FROM songs
WHERE lyrics IS NOT NULL
AND NOT is_instrumental
AND NOT is_collection
AND parent_song_id IS NULL
AND (LOWER(artists) LIKE '%martin garrix%'
   OR LOWER(artists) LIKE '%area21%'
   OR LOWER(artists) LIKE '%ytram%'
   OR LOWER(artists) LIKE '%grx%')
AND NOT (LOWER(COALESCE(mix_name, '')) LIKE '%remix%'
   AND (LOWER(mix_name) LIKE '%martin garrix%'
      OR LOWER(mix_name) LIKE '%area21%'
      OR LOWER(mix_name) LIKE '%ytram%'
      OR LOWER(mix_name) LIKE '%grx%'))
ORDER BY RANDOM()
LIMIT 1
`

// '%ytram%' was '%ytrram%'. The typo meant no Ytram song has ever been served by
// the quiz; config.toml's monitored-artist list confirms the correct spelling.
//
// Crediting one of the monitored acts is not the same as the song being theirs. On a
// remix the credit line names both acts, so "The Weeknd, Martin Garrix" matched here
// and the quiz asked people to name a Weeknd record from Weeknd lyrics -- the answer
// "Can't Feel My Face" is not a Martin Garrix song, it is a Martin Garrix remix of
// someone else's. Same for "Cocoon", which is 070 Shake's.
//
// mix_name is what separates the two cases, because it names the remixer and not the
// artist. Our act in the remixer slot means the record belongs to whoever we remixed,
// so it is dropped; anyone else there ("La La La (Drove Remix)") means one of our own
// songs in someone else's hands, whose lyrics are still ours to quiz on.
func (q *Queries) GetRandomSongWithLyrics(ctx context.Context) (Song, error) {
	row := q.db.QueryRow(ctx, getRandomSongWithLyrics)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Artists,
		&i.ThumbnailUrl,
		&i.SpotifyUrl,
		&i.AppleMusicUrl,
		&i.YoutubeUrl,
		&i.Lyrics,
		&i.IsUnreleased,
		&i.BeatportID,
		&i.MixName,
		&i.ReleaseDate,
		&i.ReleaseName,
		&i.Genre,
		&i.SubGenre,
		&i.Bpm,
		&i.MusicalKey,
		&i.LengthMs,
		&i.BeatportUpdated,
		&i.Source,
		&i.FirstSeenAt,
		&i.AnnouncedAt,
		&i.StmpdSyncedAt,
		&i.DeezerUrl,
		&i.TidalUrl,
		&i.AmazonMusicUrl,
		&i.YoutubeMusicUrl,
		&i.BeatportUrl,
		&i.BeatportReleaseID,
		&i.StmpdSlug,
		&i.MatchKey,
		&i.BaseKey,
		&i.ParentSongID,
		&i.IsInstrumental,
		&i.IsCollection,
		&i.BeatportSlug,
		&i.NormalizedName,
		&i.LrclibID,
		&i.LrclibCheckedAt,
		&i.LrclibMisses,
		&i.LockedFields,
		&i.SearchText,
	)
	return i, err
}

const getRandomSongWithLyricsEasy = `-- name: GetRandomSongWithLyricsEasy :one
SELECT id, name, artists, thumbnail_url, spotify_url, apple_music_url, youtube_url, lyrics, is_unreleased, beatport_id, mix_name, release_date, release_name, genre, sub_genre, bpm, musical_key, length_ms, beatport_updated, source, first_seen_at, announced_at, stmpd_synced_at, deezer_url, tidal_url, amazon_music_url, youtube_music_url, beatport_url, beatport_release_id, stmpd_slug, match_key, base_key, parent_song_id, is_instrumental, is_collection, beatport_slug, normalized_name, lrclib_id, lrclib_checked_at, lrclib_misses, locked_fields, search_text FROM songs
WHERE lyrics IS NOT NULL
AND NOT is_instrumental
AND NOT is_collection
AND parent_song_id IS NULL
AND LOWER(artists) LIKE '%martin garrix%'
AND NOT (LOWER(COALESCE(mix_name, '')) LIKE '%remix%'
   AND (LOWER(mix_name) LIKE '%martin garrix%'
      OR LOWER(mix_name) LIKE '%area21%'
      OR LOWER(mix_name) LIKE '%ytram%'
      OR LOWER(mix_name) LIKE '%grx%'))
ORDER BY RANDOM()
LIMIT 1
`

// Carries the same remix exclusion as GetRandomSongWithLyrics above, for the same
// reason: "easy" narrows which acts qualify, not what counts as their song.
func (q *Queries) GetRandomSongWithLyricsEasy(ctx context.Context) (Song, error) {
	row := q.db.QueryRow(ctx, getRandomSongWithLyricsEasy)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Artists,
		&i.ThumbnailUrl,
		&i.SpotifyUrl,
		&i.AppleMusicUrl,
		&i.YoutubeUrl,
		&i.Lyrics,
		&i.IsUnreleased,
		&i.BeatportID,
		&i.MixName,
		&i.ReleaseDate,
		&i.ReleaseName,
		&i.Genre,
		&i.SubGenre,
		&i.Bpm,
		&i.MusicalKey,
		&i.LengthMs,
		&i.BeatportUpdated,
		&i.Source,
		&i.FirstSeenAt,
		&i.AnnouncedAt,
		&i.StmpdSyncedAt,
		&i.DeezerUrl,
		&i.TidalUrl,
		&i.AmazonMusicUrl,
		&i.YoutubeMusicUrl,
		&i.BeatportUrl,
		&i.BeatportReleaseID,
		&i.StmpdSlug,
		&i.MatchKey,
		&i.BaseKey,
		&i.ParentSongID,
		&i.IsInstrumental,
		&i.IsCollection,
		&i.BeatportSlug,
		&i.NormalizedName,
		&i.LrclibID,
		&i.LrclibCheckedAt,
		&i.LrclibMisses,
		&i.LockedFields,
		&i.SearchText,
	)
	return i, err
}

const getSong = `-- name: GetSong :one
SELECT id, name, artists, thumbnail_url, spotify_url, apple_music_url, youtube_url, lyrics, is_unreleased, beatport_id, mix_name, release_date, release_name, genre, sub_genre, bpm, musical_key, length_ms, beatport_updated, source, first_seen_at, announced_at, stmpd_synced_at, deezer_url, tidal_url, amazon_music_url, youtube_music_url, beatport_url, beatport_release_id, stmpd_slug, match_key, base_key, parent_song_id, is_instrumental, is_collection, beatport_slug, normalized_name, lrclib_id, lrclib_checked_at, lrclib_misses, locked_fields, search_text FROM songs
WHERE name = $1 AND artists = $2 AND release_date IS NOT DISTINCT FROM $3
`

type GetSongParams struct {
	Name        string      `json:"name"`
	Artists     string      `json:"artists"`
	ReleaseDate pgtype.Text `json:"releaseDate"`
}

// IS NOT DISTINCT FROM, not "=": release_date is NULL for unreleased songs and for
// ones whose date we could not establish, and "=" never matches NULL.
func (q *Queries) GetSong(ctx context.Context, arg GetSongParams) (Song, error) {
	row := q.db.QueryRow(ctx, getSong, arg.Name, arg.Artists, arg.ReleaseDate)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Artists,
		&i.ThumbnailUrl,
		&i.SpotifyUrl,
		&i.AppleMusicUrl,
		&i.YoutubeUrl,
		&i.Lyrics,
		&i.IsUnreleased,
		&i.BeatportID,
		&i.MixName,
		&i.ReleaseDate,
		&i.ReleaseName,
		&i.Genre,
		&i.SubGenre,
		&i.Bpm,
		&i.MusicalKey,
		&i.LengthMs,
		&i.BeatportUpdated,
		&i.Source,
		&i.FirstSeenAt,
		&i.AnnouncedAt,
		&i.StmpdSyncedAt,
		&i.DeezerUrl,
		&i.TidalUrl,
		&i.AmazonMusicUrl,
		&i.YoutubeMusicUrl,
		&i.BeatportUrl,
		&i.BeatportReleaseID,
		&i.StmpdSlug,
		&i.MatchKey,
		&i.BaseKey,
		&i.ParentSongID,
		&i.IsInstrumental,
		&i.IsCollection,
		&i.BeatportSlug,
		&i.NormalizedName,
		&i.LrclibID,
		&i.LrclibCheckedAt,
		&i.LrclibMisses,
		&i.LockedFields,
		&i.SearchText,
	)
	return i, err
}

const getSongByBeatportID = `-- name: GetSongByBeatportID :one
SELECT id, name, artists, thumbnail_url, spotify_url, apple_music_url, youtube_url, lyrics, is_unreleased, beatport_id, mix_name, release_date, release_name, genre, sub_genre, bpm, musical_key, length_ms, beatport_updated, source, first_seen_at, announced_at, stmpd_synced_at, deezer_url, tidal_url, amazon_music_url, youtube_music_url, beatport_url, beatport_release_id, stmpd_slug, match_key, base_key, parent_song_id, is_instrumental, is_collection, beatport_slug, normalized_name, lrclib_id, lrclib_checked_at, lrclib_misses, locked_fields, search_text FROM songs WHERE beatport_id = $1
`

func (q *Queries) GetSongByBeatportID(ctx context.Context, beatportID pgtype.Int4) (Song, error) {
	row := q.db.QueryRow(ctx, getSongByBeatportID, beatportID)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Artists,
		&i.ThumbnailUrl,
		&i.SpotifyUrl,
		&i.AppleMusicUrl,
		&i.YoutubeUrl,
		&i.Lyrics,
		&i.IsUnreleased,
		&i.BeatportID,
		&i.MixName,
		&i.ReleaseDate,
		&i.ReleaseName,
		&i.Genre,
		&i.SubGenre,
		&i.Bpm,
		&i.MusicalKey,
		&i.LengthMs,
		&i.BeatportUpdated,
		&i.Source,
		&i.FirstSeenAt,
		&i.AnnouncedAt,
		&i.StmpdSyncedAt,
		&i.DeezerUrl,
		&i.TidalUrl,
		&i.AmazonMusicUrl,
		&i.YoutubeMusicUrl,
		&i.BeatportUrl,
		&i.BeatportReleaseID,
		&i.StmpdSlug,
		&i.MatchKey,
		&i.BaseKey,
		&i.ParentSongID,
		&i.IsInstrumental,
		&i.IsCollection,
		&i.BeatportSlug,
		&i.NormalizedName,
		&i.LrclibID,
		&i.LrclibCheckedAt,
		&i.LrclibMisses,
		&i.LockedFields,
		&i.SearchText,
	)
	return i, err
}

const getSongByID = `-- name: GetSongByID :one
SELECT id, name, artists, thumbnail_url, spotify_url, apple_music_url, youtube_url, lyrics, is_unreleased, beatport_id, mix_name, release_date, release_name, genre, sub_genre, bpm, musical_key, length_ms, beatport_updated, source, first_seen_at, announced_at, stmpd_synced_at, deezer_url, tidal_url, amazon_music_url, youtube_music_url, beatport_url, beatport_release_id, stmpd_slug, match_key, base_key, parent_song_id, is_instrumental, is_collection, beatport_slug, normalized_name, lrclib_id, lrclib_checked_at, lrclib_misses, locked_fields, search_text FROM songs WHERE id = $1
`

func (q *Queries) GetSongByID(ctx context.Context, id int64) (Song, error) {
	row := q.db.QueryRow(ctx, getSongByID, id)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Artists,
		&i.ThumbnailUrl,
		&i.SpotifyUrl,
		&i.AppleMusicUrl,
		&i.YoutubeUrl,
		&i.Lyrics,
		&i.IsUnreleased,
		&i.BeatportID,
		&i.MixName,
		&i.ReleaseDate,
		&i.ReleaseName,
		&i.Genre,
		&i.SubGenre,
		&i.Bpm,
		&i.MusicalKey,
		&i.LengthMs,
		&i.BeatportUpdated,
		&i.Source,
		&i.FirstSeenAt,
		&i.AnnouncedAt,
		&i.StmpdSyncedAt,
		&i.DeezerUrl,
		&i.TidalUrl,
		&i.AmazonMusicUrl,
		&i.YoutubeMusicUrl,
		&i.BeatportUrl,
		&i.BeatportReleaseID,
		&i.StmpdSlug,
		&i.MatchKey,
		&i.BaseKey,
		&i.ParentSongID,
		&i.IsInstrumental,
		&i.IsCollection,
		&i.BeatportSlug,
		&i.NormalizedName,
		&i.LrclibID,
		&i.LrclibCheckedAt,
		&i.LrclibMisses,
		&i.LockedFields,
		&i.SearchText,
	)
	return i, err
}

const getSongByStmpdSlug = `-- name: GetSongByStmpdSlug :one
SELECT id, name, artists, thumbnail_url, spotify_url, apple_music_url, youtube_url, lyrics, is_unreleased, beatport_id, mix_name, release_date, release_name, genre, sub_genre, bpm, musical_key, length_ms, beatport_updated, source, first_seen_at, announced_at, stmpd_synced_at, deezer_url, tidal_url, amazon_music_url, youtube_music_url, beatport_url, beatport_release_id, stmpd_slug, match_key, base_key, parent_song_id, is_instrumental, is_collection, beatport_slug, normalized_name, lrclib_id, lrclib_checked_at, lrclib_misses, locked_fields, search_text FROM songs WHERE stmpd_slug = $1
`

func (q *Queries) GetSongByStmpdSlug(ctx context.Context, stmpdSlug pgtype.Text) (Song, error) {
	row := q.db.QueryRow(ctx, getSongByStmpdSlug, stmpdSlug)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Artists,
		&i.ThumbnailUrl,
		&i.SpotifyUrl,
		&i.AppleMusicUrl,
		&i.YoutubeUrl,
		&i.Lyrics,
		&i.IsUnreleased,
		&i.BeatportID,
		&i.MixName,
		&i.ReleaseDate,
		&i.ReleaseName,
		&i.Genre,
		&i.SubGenre,
		&i.Bpm,
		&i.MusicalKey,
		&i.LengthMs,
		&i.BeatportUpdated,
		&i.Source,
		&i.FirstSeenAt,
		&i.AnnouncedAt,
		&i.StmpdSyncedAt,
		&i.DeezerUrl,
		&i.TidalUrl,
		&i.AmazonMusicUrl,
		&i.YoutubeMusicUrl,
		&i.BeatportUrl,
		&i.BeatportReleaseID,
		&i.StmpdSlug,
		&i.MatchKey,
		&i.BaseKey,
		&i.ParentSongID,
		&i.IsInstrumental,
		&i.IsCollection,
		&i.BeatportSlug,
		&i.NormalizedName,
		&i.LrclibID,
		&i.LrclibCheckedAt,
		&i.LrclibMisses,
		&i.LockedFields,
		&i.SearchText,
	)
	return i, err
}

const getSongMixes = `-- name: GetSongMixes :many
SELECT id, name, mix_name, artists, release_date, thumbnail_url, source,
       spotify_url, youtube_url, apple_music_url, beatport_url,
       (lyrics IS NOT NULL)::boolean AS has_lyrics
FROM songs
WHERE parent_song_id = $1 ORDER BY release_date, id
`

type GetSongMixesRow struct {
	ID            int64       `json:"id"`
	Name          string      `json:"name"`
	MixName       pgtype.Text `json:"mixName"`
	Artists       string      `json:"artists"`
	ReleaseDate   pgtype.Text `json:"releaseDate"`
	ThumbnailUrl  pgtype.Text `json:"thumbnailUrl"`
	Source        string      `json:"source"`
	SpotifyUrl    pgtype.Text `json:"spotifyUrl"`
	YoutubeUrl    pgtype.Text `json:"youtubeUrl"`
	AppleMusicUrl pgtype.Text `json:"appleMusicUrl"`
	BeatportUrl   pgtype.Text `json:"beatportUrl"`
	HasLyrics     bool        `json:"hasLyrics"`
}

// The renditions hanging off a canonical song, for the track card and the dashboard's
// song page to list.
//
// The link and lyric columns are selected so a reader can see at a glance that a
// rendition carries something its canonical row does not -- which is exactly the
// defect that hid "Break Through The Silence"'s streaming links behind a linkless
// beatport row, and is the button that promotes the better row.
func (q *Queries) GetSongMixes(ctx context.Context, parentSongID pgtype.Int8) ([]GetSongMixesRow, error) {
	rows, err := q.db.Query(ctx, getSongMixes, parentSongID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSongMixesRow
	for rows.Next() {
		var i GetSongMixesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MixName,
			&i.Artists,
			&i.ReleaseDate,
			&i.ThumbnailUrl,
			&i.Source,
			&i.SpotifyUrl,
			&i.YoutubeUrl,
			&i.AppleMusicUrl,
			&i.BeatportUrl,
			&i.HasLyrics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongsForAudit = `-- name: GetSongsForAudit :many
SELECT id, name, artists, mix_name, length_ms, is_collection, parent_song_id,
       match_key, base_key, normalized_name, search_text, release_date,
       apple_music_url, spotify_url, youtube_url, stmpd_slug,
       beatport_id, beatport_slug, beatport_url, deezer_url, tidal_url,
       amazon_music_url, youtube_music_url, source,
       thumbnail_url, is_instrumental, is_unreleased, locked_fields, release_name,
       (lyrics IS NOT NULL)::boolean AS has_lyrics
FROM songs ORDER BY id
`

type GetSongsForAuditRow struct {
	ID              int64       `json:"id"`
	Name            string      `json:"name"`
	Artists         string      `json:"artists"`
	MixName         pgtype.Text `json:"mixName"`
	LengthMs        pgtype.Int4 `json:"lengthMs"`
	IsCollection    bool        `json:"isCollection"`
	ParentSongID    pgtype.Int8 `json:"parentSongId"`
	MatchKey        pgtype.Text `json:"matchKey"`
	BaseKey         pgtype.Text `json:"baseKey"`
	NormalizedName  pgtype.Text `json:"normalizedName"`
	SearchText      pgtype.Text `json:"searchText"`
	ReleaseDate     pgtype.Text `json:"releaseDate"`
	AppleMusicUrl   pgtype.Text `json:"appleMusicUrl"`
	SpotifyUrl      pgtype.Text `json:"spotifyUrl"`
	YoutubeUrl      pgtype.Text `json:"youtubeUrl"`
	StmpdSlug       pgtype.Text `json:"stmpdSlug"`
	BeatportID      pgtype.Int4 `json:"beatportId"`
	BeatportSlug    pgtype.Text `json:"beatportSlug"`
	BeatportUrl     pgtype.Text `json:"beatportUrl"`
	DeezerUrl       pgtype.Text `json:"deezerUrl"`
	TidalUrl        pgtype.Text `json:"tidalUrl"`
	AmazonMusicUrl  pgtype.Text `json:"amazonMusicUrl"`
	YoutubeMusicUrl pgtype.Text `json:"youtubeMusicUrl"`
	Source          string      `json:"source"`
	ThumbnailUrl    pgtype.Text `json:"thumbnailUrl"`
	IsInstrumental  bool        `json:"isInstrumental"`
	IsUnreleased    bool        `json:"isUnreleased"`
	LockedFields    []string    `json:"lockedFields"`
	ReleaseName     pgtype.Text `json:"releaseName"`
	HasLyrics       bool        `json:"hasLyrics"`
}

// Everything the invariant checker needs to recompute a row's derived state and
// compare it against what is stored.
func (q *Queries) GetSongsForAudit(ctx context.Context) ([]GetSongsForAuditRow, error) {
	rows, err := q.db.Query(ctx, getSongsForAudit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSongsForAuditRow
	for rows.Next() {
		var i GetSongsForAuditRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.MixName,
			&i.LengthMs,
			&i.IsCollection,
			&i.ParentSongID,
			&i.MatchKey,
			&i.BaseKey,
			&i.NormalizedName,
			&i.SearchText,
			&i.ReleaseDate,
			&i.AppleMusicUrl,
			&i.SpotifyUrl,
			&i.YoutubeUrl,
			&i.StmpdSlug,
			&i.BeatportID,
			&i.BeatportSlug,
			&i.BeatportUrl,
			&i.DeezerUrl,
			&i.TidalUrl,
			&i.AmazonMusicUrl,
			&i.YoutubeMusicUrl,
			&i.Source,
			&i.ThumbnailUrl,
			&i.IsInstrumental,
			&i.IsUnreleased,
			&i.LockedFields,
			&i.ReleaseName,
			&i.HasLyrics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongsForKeying = `-- name: GetSongsForKeying :many
SELECT id, name, artists, mix_name, length_ms, is_collection, apple_music_url, stmpd_slug,
       normalized_name, release_name, search_text
FROM songs ORDER BY id
`

type GetSongsForKeyingRow struct {
	ID             int64       `json:"id"`
	Name           string      `json:"name"`
	Artists        string      `json:"artists"`
	MixName        pgtype.Text `json:"mixName"`
	LengthMs       pgtype.Int4 `json:"lengthMs"`
	IsCollection   bool        `json:"isCollection"`
	AppleMusicUrl  pgtype.Text `json:"appleMusicUrl"`
	StmpdSlug      pgtype.Text `json:"stmpdSlug"`
	NormalizedName pgtype.Text `json:"normalizedName"`
	ReleaseName    pgtype.Text `json:"releaseName"`
	SearchText     pgtype.Text `json:"searchText"`
}

// release_name is selected because search_text folds it in: it is how someone looks
// for a track by the EP it came on, which is often all they remember of it.
func (q *Queries) GetSongsForKeying(ctx context.Context) ([]GetSongsForKeyingRow, error) {
	rows, err := q.db.Query(ctx, getSongsForKeying)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSongsForKeyingRow
	for rows.Next() {
		var i GetSongsForKeyingRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.MixName,
			&i.LengthMs,
			&i.IsCollection,
			&i.AppleMusicUrl,
			&i.StmpdSlug,
			&i.NormalizedName,
			&i.ReleaseName,
			&i.SearchText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongsForParentLinking = `-- name: GetSongsForParentLinking :many
SELECT id, name, artists, mix_name, release_date, source, base_key, stmpd_slug,
       spotify_url, youtube_url, apple_music_url, lyrics, parent_song_id, is_collection,
       locked_fields
FROM songs ORDER BY id
`

type GetSongsForParentLinkingRow struct {
	ID            int64       `json:"id"`
	Name          string      `json:"name"`
	Artists       string      `json:"artists"`
	MixName       pgtype.Text `json:"mixName"`
	ReleaseDate   pgtype.Text `json:"releaseDate"`
	Source        string      `json:"source"`
	BaseKey       pgtype.Text `json:"baseKey"`
	StmpdSlug     pgtype.Text `json:"stmpdSlug"`
	SpotifyUrl    pgtype.Text `json:"spotifyUrl"`
	YoutubeUrl    pgtype.Text `json:"youtubeUrl"`
	AppleMusicUrl pgtype.Text `json:"appleMusicUrl"`
	Lyrics        pgtype.Text `json:"lyrics"`
	ParentSongID  pgtype.Int8 `json:"parentSongId"`
	IsCollection  bool        `json:"isCollection"`
	LockedFields  []string    `json:"lockedFields"`
}

// stmpd_slug is selected because electing a canonical row weighs provenance first, and
// a column that is not in the row cannot be weighed. Leaving it out is what let a
// beatport row with no links win over the STMPD row for the same song.
func (q *Queries) GetSongsForParentLinking(ctx context.Context) ([]GetSongsForParentLinkingRow, error) {
	rows, err := q.db.Query(ctx, getSongsForParentLinking)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSongsForParentLinkingRow
	for rows.Next() {
		var i GetSongsForParentLinkingRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.MixName,
			&i.ReleaseDate,
			&i.Source,
			&i.BaseKey,
			&i.StmpdSlug,
			&i.SpotifyUrl,
			&i.YoutubeUrl,
			&i.AppleMusicUrl,
			&i.Lyrics,
			&i.ParentSongID,
			&i.IsCollection,
			&i.LockedFields,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongsForSubsetDedupe = `-- name: GetSongsForSubsetDedupe :many
SELECT id, name, artists, mix_name, release_date, source, stmpd_slug, beatport_id,
       spotify_url, apple_music_url, youtube_url, lyrics, parent_song_id, is_collection
FROM songs ORDER BY id
`

type GetSongsForSubsetDedupeRow struct {
	ID            int64       `json:"id"`
	Name          string      `json:"name"`
	Artists       string      `json:"artists"`
	MixName       pgtype.Text `json:"mixName"`
	ReleaseDate   pgtype.Text `json:"releaseDate"`
	Source        string      `json:"source"`
	StmpdSlug     pgtype.Text `json:"stmpdSlug"`
	BeatportID    pgtype.Int4 `json:"beatportId"`
	SpotifyUrl    pgtype.Text `json:"spotifyUrl"`
	AppleMusicUrl pgtype.Text `json:"appleMusicUrl"`
	YoutubeUrl    pgtype.Text `json:"youtubeUrl"`
	Lyrics        pgtype.Text `json:"lyrics"`
	ParentSongID  pgtype.Int8 `json:"parentSongId"`
	IsCollection  bool        `json:"isCollection"`
}

// Everything needed to spot rows that are the same recording credited to different
// subsets of the same artists.
func (q *Queries) GetSongsForSubsetDedupe(ctx context.Context) ([]GetSongsForSubsetDedupeRow, error) {
	rows, err := q.db.Query(ctx, getSongsForSubsetDedupe)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSongsForSubsetDedupeRow
	for rows.Next() {
		var i GetSongsForSubsetDedupeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.MixName,
			&i.ReleaseDate,
			&i.Source,
			&i.StmpdSlug,
			&i.BeatportID,
			&i.SpotifyUrl,
			&i.AppleMusicUrl,
			&i.YoutubeUrl,
			&i.Lyrics,
			&i.ParentSongID,
			&i.IsCollection,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongsLike = `-- name: GetSongsLike :many
SELECT id, name, artists, mix_name, release_date
FROM songs
WHERE NOT is_collection
  AND COALESCE(search_text,
               LOWER(artists || ' ' || name || ' ' || COALESCE(mix_name, '')))
        LIKE ALL ($1::text[])
ORDER BY (parent_song_id IS NOT NULL), release_date DESC
LIMIT 20
`

type GetSongsLikeRow struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	Artists     string      `json:"artists"`
	MixName     pgtype.Text `json:"mixName"`
	ReleaseDate pgtype.Text `json:"releaseDate"`
}

// Renditions are listed, not hidden. A remix is its own recording with its own links,
// and excluding it made those links unreachable through the bot at all. What made the
// old list unusable was the same song appearing twice under one name -- that is a
// duplicate, and duplicates are merged rather than filtered out of sight.
//
// Collections are still excluded: an EP is not something to fetch links for as a song.
// mix_name comes back so the caller can tell two renditions apart in the label.
//
// Matching is per term against the folded haystack, not one contiguous LIKE over the
// raw columns. The old form could not find "Don't Tell Me" by "Matisse & Sadko, Aspyer,
// Matluck" from "matisse sadko dont tell me": every word is in the row, but not
// adjacent and not in that order, so the song read as missing from the catalogue.
//
// COALESCE onto an unfolded expression so a row inserted before the next rekey-songs is
// still findable, just without accent and apostrophe folding.
func (q *Queries) GetSongsLike(ctx context.Context, terms []string) ([]GetSongsLikeRow, error) {
	rows, err := q.db.Query(ctx, getSongsLike, terms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSongsLikeRow
	for rows.Next() {
		var i GetSongsLikeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.MixName,
			&i.ReleaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongsMissingArtwork = `-- name: GetSongsMissingArtwork :many
SELECT id, name, artists, apple_music_url
FROM songs WHERE coalesce(thumbnail_url, '') = ''
ORDER BY (apple_music_url IS NULL), id
`

type GetSongsMissingArtworkRow struct {
	ID            int64       `json:"id"`
	Name          string      `json:"name"`
	Artists       string      `json:"artists"`
	AppleMusicUrl pgtype.Text `json:"appleMusicUrl"`
}

// Rows with no cover art. Beatport cannot help with these: every row it knows about
// already has artwork, and none of these carry a beatport_id. Apple can -- most of
// them have an Apple link, and the lookup returns a cover.
func (q *Queries) GetSongsMissingArtwork(ctx context.Context) ([]GetSongsMissingArtworkRow, error) {
	rows, err := q.db.Query(ctx, getSongsMissingArtwork)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSongsMissingArtworkRow
	for rows.Next() {
		var i GetSongsMissingArtworkRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.AppleMusicUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongsMissingBeatportSlug = `-- name: GetSongsMissingBeatportSlug :many
SELECT id, name, artists, mix_name, beatport_id FROM songs
WHERE beatport_id IS NOT NULL AND beatport_slug IS NULL ORDER BY id
`

type GetSongsMissingBeatportSlugRow struct {
	ID         int64       `json:"id"`
	Name       string      `json:"name"`
	Artists    string      `json:"artists"`
	MixName    pgtype.Text `json:"mixName"`
	BeatportID pgtype.Int4 `json:"beatportId"`
}

// Rows carrying a Beatport track id whose page URL cannot be built yet.
func (q *Queries) GetSongsMissingBeatportSlug(ctx context.Context) ([]GetSongsMissingBeatportSlugRow, error) {
	rows, err := q.db.Query(ctx, getSongsMissingBeatportSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSongsMissingBeatportSlugRow
	for rows.Next() {
		var i GetSongsMissingBeatportSlugRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.MixName,
			&i.BeatportID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongsMissingLinks = `-- name: GetSongsMissingLinks :many
SELECT id, name, artists, release_date, source, beatport_id
FROM songs WHERE stmpd_synced_at IS NULL ORDER BY id
`

type GetSongsMissingLinksRow struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	Artists     string      `json:"artists"`
	ReleaseDate pgtype.Text `json:"releaseDate"`
	Source      string      `json:"source"`
	BeatportID  pgtype.Int4 `json:"beatportId"`
}

// The backfill queue: rows the STMPD sync has never successfully applied to. After
// migration 000009 this is exactly the set of rows carrying no streaming links.
func (q *Queries) GetSongsMissingLinks(ctx context.Context) ([]GetSongsMissingLinksRow, error) {
	rows, err := q.db.Query(ctx, getSongsMissingLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSongsMissingLinksRow
	for rows.Next() {
		var i GetSongsMissingLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.ReleaseDate,
			&i.Source,
			&i.BeatportID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongsMissingLyrics = `-- name: GetSongsMissingLyrics :many
SELECT id, name, artists, mix_name, normalized_name, release_name, length_ms, lrclib_misses
FROM songs
WHERE lyrics IS NULL
  AND NOT is_instrumental
  AND NOT is_collection
  AND parent_song_id IS NULL
  AND lrclib_misses < 4
  AND (lrclib_checked_at IS NULL
       OR lrclib_checked_at < NOW() - (INTERVAL '7 days' * POWER(4, lrclib_misses)))
ORDER BY lrclib_checked_at NULLS FIRST, release_date DESC NULLS LAST, id
LIMIT $1
`

type GetSongsMissingLyricsRow struct {
	ID             int64       `json:"id"`
	Name           string      `json:"name"`
	Artists        string      `json:"artists"`
	MixName        pgtype.Text `json:"mixName"`
	NormalizedName pgtype.Text `json:"normalizedName"`
	ReleaseName    pgtype.Text `json:"releaseName"`
	LengthMs       pgtype.Int4 `json:"lengthMs"`
	LrclibMisses   int16       `json:"lrclibMisses"`
}

// The LRCLIB backlog.
//
// Canonical rows only: a rendition inherits its parent's words through
// CopyLyricsToRemixes, so asking LRCLIB separately about each of a song's twelve
// remixes is twelve times the requests for one answer.
//
// The retry schedule widens with every miss -- 7 days, 28, 112, 448 -- and gives up
// after four. LRCLIB is community-contributed and does grow, so "never again" is
// wrong; but a row that has come up empty four times over a year and a half is not
// going to be filled by asking a fifth.
//
// Newest first among never-asked rows, because a song released this month is the one
// people will actually be quizzed on and the one most likely to have just been added
// upstream.
func (q *Queries) GetSongsMissingLyrics(ctx context.Context, lim int32) ([]GetSongsMissingLyricsRow, error) {
	rows, err := q.db.Query(ctx, getSongsMissingLyrics, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSongsMissingLyricsRow
	for rows.Next() {
		var i GetSongsMissingLyricsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.MixName,
			&i.NormalizedName,
			&i.ReleaseName,
			&i.LengthMs,
			&i.LrclibMisses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongsNeedingYoutube = `-- name: GetSongsNeedingYoutube :many
SELECT id, name, artists, mix_name, youtube_url, spotify_url
FROM songs
WHERE youtube_url IS NULL
   OR (youtube_url NOT LIKE '%watch?v=%' AND youtube_url NOT LIKE '%youtu.be/%')
ORDER BY id
`

type GetSongsNeedingYoutubeRow struct {
	ID         int64       `json:"id"`
	Name       string      `json:"name"`
	Artists    string      `json:"artists"`
	MixName    pgtype.Text `json:"mixName"`
	YoutubeUrl pgtype.Text `json:"youtubeUrl"`
	SpotifyUrl pgtype.Text `json:"spotifyUrl"`
}

// Rows whose YouTube button is missing or points at a playlist rather than a video.
// A playlist link is worse than none: it sends people to a playlist instead of the
// song they asked for.
// youtu.be short links are perfectly good videos -- the radio already follows them
// -- so they are not "missing". Only a genuine playlist or an absent link is.
func (q *Queries) GetSongsNeedingYoutube(ctx context.Context) ([]GetSongsNeedingYoutubeRow, error) {
	rows, err := q.db.Query(ctx, getSongsNeedingYoutube)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSongsNeedingYoutubeRow
	for rows.Next() {
		var i GetSongsNeedingYoutubeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.MixName,
			&i.YoutubeUrl,
			&i.SpotifyUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongsNeverAnnounced = `-- name: GetSongsNeverAnnounced :many
SELECT id, name, artists, release_date FROM songs WHERE announced_at IS NULL
`

type GetSongsNeverAnnouncedRow struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	Artists     string      `json:"artists"`
	ReleaseDate pgtype.Text `json:"releaseDate"`
}

func (q *Queries) GetSongsNeverAnnounced(ctx context.Context) ([]GetSongsNeverAnnouncedRow, error) {
	rows, err := q.db.Query(ctx, getSongsNeverAnnounced)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSongsNeverAnnouncedRow
	for rows.Next() {
		var i GetSongsNeverAnnouncedRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.ReleaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongsToCheckForCollection = `-- name: GetSongsToCheckForCollection :many
SELECT id, name, artists, apple_music_url
FROM songs
WHERE NOT is_collection AND apple_music_url IS NOT NULL
  AND apple_music_url NOT LIKE '%/playlist/%'
ORDER BY id
`

type GetSongsToCheckForCollectionRow struct {
	ID            int64       `json:"id"`
	Name          string      `json:"name"`
	Artists       string      `json:"artists"`
	AppleMusicUrl pgtype.Text `json:"appleMusicUrl"`
}

// Rows not yet known to be releases, that carry an Apple link we can ask about.
func (q *Queries) GetSongsToCheckForCollection(ctx context.Context) ([]GetSongsToCheckForCollectionRow, error) {
	rows, err := q.db.Query(ctx, getSongsToCheckForCollection)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSongsToCheckForCollectionRow
	for rows.Next() {
		var i GetSongsToCheckForCollectionRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.AppleMusicUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongsWithACheckableDate = `-- name: GetSongsWithACheckableDate :many
SELECT id, name, artists, mix_name, release_date, apple_music_url
FROM songs
WHERE release_date IS NOT NULL
  AND release_date <> '1970-01-01'
  AND COALESCE(apple_music_url, '') <> ''
  AND NOT ('release_date' = ANY(locked_fields))
ORDER BY id
`

type GetSongsWithACheckableDateRow struct {
	ID            int64       `json:"id"`
	Name          string      `json:"name"`
	Artists       string      `json:"artists"`
	MixName       pgtype.Text `json:"mixName"`
	ReleaseDate   pgtype.Text `json:"releaseDate"`
	AppleMusicUrl pgtype.Text `json:"appleMusicUrl"`
}

// Every row whose stored date can be checked against the recording it links to.
//
// The placeholder query above asks "which rows have no date"; this one asks "which
// rows have a date that might be the wrong one", which turned out to be the more
// expensive question. A date can be a real date, in range, and still describe the
// wrong event -- beatport's publish_date on a re-delivered back catalogue is a real
// date, and it is how a 2012 remix came to be announced as a 2021 release.
//
// Locked rows are excluded: a person has already ruled on those, and re-reporting
// them every run is how a report stops being read.
func (q *Queries) GetSongsWithACheckableDate(ctx context.Context) ([]GetSongsWithACheckableDateRow, error) {
	rows, err := q.db.Query(ctx, getSongsWithACheckableDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSongsWithACheckableDateRow
	for rows.Next() {
		var i GetSongsWithACheckableDateRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.MixName,
			&i.ReleaseDate,
			&i.AppleMusicUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongsWithLyricsLike = `-- name: GetSongsWithLyricsLike :many
SELECT id, name, artists, mix_name, release_date
FROM songs
WHERE lyrics IS NOT NULL
  AND NOT is_collection
  AND parent_song_id IS NULL
  AND COALESCE(search_text,
               LOWER(artists || ' ' || name || ' ' || COALESCE(mix_name, '')))
        LIKE ALL ($1::text[])
ORDER BY release_date DESC
LIMIT 20
`

type GetSongsWithLyricsLikeRow struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	Artists     string      `json:"artists"`
	MixName     pgtype.Text `json:"mixName"`
	ReleaseDate pgtype.Text `json:"releaseDate"`
}

// Canonical rows only, which is the opposite of what GetSongsLike does and is
// deliberate. A remix carries its own streaming links, so /links has to list it; a
// remix's words are byte-identical to the original's, so listing it in /lyrics is
// eighteen ways to read the same page.
//
// This became visible when the LRCLIB backfill fanned lyrics out to renditions:
// searching "scared to be lonely" returned the song plus seventeen of its remixes and
// pushed everything else past Discord's 20-choice limit. Before the fan-out only the
// canonical row had lyrics, so the missing filter never showed.
//
// GetRandomSongNamesWithLyrics, which answers the same autocomplete on empty input,
// has always filtered this way. The two now agree.
//
// Term matching is the same as GetSongsLike; see the note there.
func (q *Queries) GetSongsWithLyricsLike(ctx context.Context, terms []string) ([]GetSongsWithLyricsLikeRow, error) {
	rows, err := q.db.Query(ctx, getSongsWithLyricsLike, terms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSongsWithLyricsLikeRow
	for rows.Next() {
		var i GetSongsWithLyricsLikeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.MixName,
			&i.ReleaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongsWithPlaceholderDate = `-- name: GetSongsWithPlaceholderDate :many
SELECT id, name, artists, release_date, apple_music_url, spotify_url
FROM songs WHERE release_date = '1970-01-01' OR release_date LIKE '%-01-01'
ORDER BY (apple_music_url IS NULL), id
`

type GetSongsWithPlaceholderDateRow struct {
	ID            int64       `json:"id"`
	Name          string      `json:"name"`
	Artists       string      `json:"artists"`
	ReleaseDate   pgtype.Text `json:"releaseDate"`
	AppleMusicUrl pgtype.Text `json:"appleMusicUrl"`
	SpotifyUrl    pgtype.Text `json:"spotifyUrl"`
}

// Rows whose release date is not a real date: the 1970-01-01 sentinel the original
// importer wrote when it had none, and rows dated the 1st of January, which is what
// the year-only scrape produced before the dataset gave exact dates.
// Ordered so the ones resolvable from a stored link come first.
func (q *Queries) GetSongsWithPlaceholderDate(ctx context.Context) ([]GetSongsWithPlaceholderDateRow, error) {
	rows, err := q.db.Query(ctx, getSongsWithPlaceholderDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSongsWithPlaceholderDateRow
	for rows.Next() {
		var i GetSongsWithPlaceholderDateRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.ReleaseDate,
			&i.AppleMusicUrl,
			&i.SpotifyUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongsWithSharedArtwork = `-- name: GetSongsWithSharedArtwork :many
SELECT id, name, artists, mix_name, release_name, thumbnail_url, source,
       apple_music_url, locked_fields
FROM songs
WHERE COALESCE(thumbnail_url, '') <> ''
  AND thumbnail_url IN (
      SELECT thumbnail_url FROM songs
      WHERE COALESCE(thumbnail_url, '') <> ''
      GROUP BY thumbnail_url
      HAVING count(DISTINCT COALESCE(parent_song_id, id)) > 1)
ORDER BY thumbnail_url, id
`

type GetSongsWithSharedArtworkRow struct {
	ID            int64       `json:"id"`
	Name          string      `json:"name"`
	Artists       string      `json:"artists"`
	MixName       pgtype.Text `json:"mixName"`
	ReleaseName   pgtype.Text `json:"releaseName"`
	ThumbnailUrl  pgtype.Text `json:"thumbnailUrl"`
	Source        string      `json:"source"`
	AppleMusicUrl pgtype.Text `json:"appleMusicUrl"`
	LockedFields  []string    `json:"lockedFields"`
}

// Rows wearing a cover that also sits on a different song.
//
// Sharing is counted per rendition family rather than per row: a song and its own
// remixes share a cover legitimately, and they do not share a base key, because beatport
// credits a remix to the original artists plus the remixer. Grouping on the family root
// -- the parent id, or the row's own id when it is canonical -- is what tells "one
// single's artwork across its versions" from "one compilation's cover across its
// tracks".
func (q *Queries) GetSongsWithSharedArtwork(ctx context.Context) ([]GetSongsWithSharedArtworkRow, error) {
	rows, err := q.db.Query(ctx, getSongsWithSharedArtwork)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSongsWithSharedArtworkRow
	for rows.Next() {
		var i GetSongsWithSharedArtworkRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.MixName,
			&i.ReleaseName,
			&i.ThumbnailUrl,
			&i.Source,
			&i.AppleMusicUrl,
			&i.LockedFields,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSongsWithUntidyYoutubeURL = `-- name: GetSongsWithUntidyYoutubeURL :many
SELECT id, youtube_url FROM songs
WHERE youtube_url IS NOT NULL
  AND (youtube_url LIKE '%youtu.be/%' OR youtube_url LIKE '%si=%' OR youtube_url LIKE '%&t=%')
ORDER BY id
`

type GetSongsWithUntidyYoutubeURLRow struct {
	ID         int64       `json:"id"`
	YoutubeUrl pgtype.Text `json:"youtubeUrl"`
}

// Rows whose link is a video but not in canonical form: a short link, or one carrying
// share tracking. Rewriting them makes every query and report agree on what a video
// looks like.
func (q *Queries) GetSongsWithUntidyYoutubeURL(ctx context.Context) ([]GetSongsWithUntidyYoutubeURLRow, error) {
	rows, err := q.db.Query(ctx, getSongsWithUntidyYoutubeURL)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSongsWithUntidyYoutubeURLRow
	for rows.Next() {
		var i GetSongsWithUntidyYoutubeURLRow
		if err := rows.Scan(&i.ID, &i.YoutubeUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreleasedSongs = `-- name: GetUnreleasedSongs :many
SELECT id, name, artists, lyrics IS NOT NULL AS has_lyrics, first_seen_at
FROM songs WHERE is_unreleased ORDER BY first_seen_at DESC, id
`

type GetUnreleasedSongsRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Artists     string             `json:"artists"`
	HasLyrics   interface{}        `json:"hasLyrics"`
	FirstSeenAt pgtype.Timestamptz `json:"firstSeenAt"`
}

func (q *Queries) GetUnreleasedSongs(ctx context.Context) ([]GetUnreleasedSongsRow, error) {
	rows, err := q.db.Query(ctx, getUnreleasedSongs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnreleasedSongsRow
	for rows.Next() {
		var i GetUnreleasedSongsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.HasLyrics,
			&i.FirstSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBeatportSong = `-- name: InsertBeatportSong :one
INSERT INTO songs (
    name, artists, release_date, thumbnail_url, beatport_id, mix_name,
    release_name, genre, sub_genre, bpm, musical_key, length_ms, beatport_slug, source
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, 'beatport')
RETURNING id, name, artists, thumbnail_url, spotify_url, apple_music_url, youtube_url, lyrics, is_unreleased, beatport_id, mix_name, release_date, release_name, genre, sub_genre, bpm, musical_key, length_ms, beatport_updated, source, first_seen_at, announced_at, stmpd_synced_at, deezer_url, tidal_url, amazon_music_url, youtube_music_url, beatport_url, beatport_release_id, stmpd_slug, match_key, base_key, parent_song_id, is_instrumental, is_collection, beatport_slug, normalized_name, lrclib_id, lrclib_checked_at, lrclib_misses, locked_fields, search_text
`

type InsertBeatportSongParams struct {
	Name         string      `json:"name"`
	Artists      string      `json:"artists"`
	ReleaseDate  pgtype.Text `json:"releaseDate"`
	ThumbnailUrl pgtype.Text `json:"thumbnailUrl"`
	BeatportID   pgtype.Int4 `json:"beatportId"`
	MixName      pgtype.Text `json:"mixName"`
	ReleaseName  pgtype.Text `json:"releaseName"`
	Genre        pgtype.Text `json:"genre"`
	SubGenre     pgtype.Text `json:"subGenre"`
	Bpm          pgtype.Int4 `json:"bpm"`
	MusicalKey   pgtype.Text `json:"musicalKey"`
	LengthMs     pgtype.Int4 `json:"lengthMs"`
	BeatportSlug pgtype.Text `json:"beatportSlug"`
}

func (q *Queries) InsertBeatportSong(ctx context.Context, arg InsertBeatportSongParams) (Song, error) {
	row := q.db.QueryRow(ctx, insertBeatportSong,
		arg.Name,
		arg.Artists,
		arg.ReleaseDate,
		arg.ThumbnailUrl,
		arg.BeatportID,
		arg.MixName,
		arg.ReleaseName,
		arg.Genre,
		arg.SubGenre,
		arg.Bpm,
		arg.MusicalKey,
		arg.LengthMs,
		arg.BeatportSlug,
	)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Artists,
		&i.ThumbnailUrl,
		&i.SpotifyUrl,
		&i.AppleMusicUrl,
		&i.YoutubeUrl,
		&i.Lyrics,
		&i.IsUnreleased,
		&i.BeatportID,
		&i.MixName,
		&i.ReleaseDate,
		&i.ReleaseName,
		&i.Genre,
		&i.SubGenre,
		&i.Bpm,
		&i.MusicalKey,
		&i.LengthMs,
		&i.BeatportUpdated,
		&i.Source,
		&i.FirstSeenAt,
		&i.AnnouncedAt,
		&i.StmpdSyncedAt,
		&i.DeezerUrl,
		&i.TidalUrl,
		&i.AmazonMusicUrl,
		&i.YoutubeMusicUrl,
		&i.BeatportUrl,
		&i.BeatportReleaseID,
		&i.StmpdSlug,
		&i.MatchKey,
		&i.BaseKey,
		&i.ParentSongID,
		&i.IsInstrumental,
		&i.IsCollection,
		&i.BeatportSlug,
		&i.NormalizedName,
		&i.LrclibID,
		&i.LrclibCheckedAt,
		&i.LrclibMisses,
		&i.LockedFields,
		&i.SearchText,
	)
	return i, err
}

const insertRelease = `-- name: InsertRelease :one
INSERT INTO songs (
    name, artists, mix_name, release_date, thumbnail_url, stmpd_slug,
    spotify_url, apple_music_url, youtube_url, youtube_music_url,
    deezer_url, tidal_url, amazon_music_url, beatport_url, beatport_release_id,
    stmpd_synced_at, source
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13,
    $14, $15,
    NOW(), 'stmpd'
)
RETURNING id, name, artists, thumbnail_url, spotify_url, apple_music_url, youtube_url, lyrics, is_unreleased, beatport_id, mix_name, release_date, release_name, genre, sub_genre, bpm, musical_key, length_ms, beatport_updated, source, first_seen_at, announced_at, stmpd_synced_at, deezer_url, tidal_url, amazon_music_url, youtube_music_url, beatport_url, beatport_release_id, stmpd_slug, match_key, base_key, parent_song_id, is_instrumental, is_collection, beatport_slug, normalized_name, lrclib_id, lrclib_checked_at, lrclib_misses, locked_fields, search_text
`

type InsertReleaseParams struct {
	Name              string      `json:"name"`
	Artists           string      `json:"artists"`
	MixName           pgtype.Text `json:"mixName"`
	ReleaseDate       pgtype.Text `json:"releaseDate"`
	ThumbnailUrl      pgtype.Text `json:"thumbnailUrl"`
	StmpdSlug         pgtype.Text `json:"stmpdSlug"`
	SpotifyUrl        pgtype.Text `json:"spotifyUrl"`
	AppleMusicUrl     pgtype.Text `json:"appleMusicUrl"`
	YoutubeUrl        pgtype.Text `json:"youtubeUrl"`
	YoutubeMusicUrl   pgtype.Text `json:"youtubeMusicUrl"`
	DeezerUrl         pgtype.Text `json:"deezerUrl"`
	TidalUrl          pgtype.Text `json:"tidalUrl"`
	AmazonMusicUrl    pgtype.Text `json:"amazonMusicUrl"`
	BeatportUrl       pgtype.Text `json:"beatportUrl"`
	BeatportReleaseID pgtype.Int4 `json:"beatportReleaseId"`
}

func (q *Queries) InsertRelease(ctx context.Context, arg InsertReleaseParams) (Song, error) {
	row := q.db.QueryRow(ctx, insertRelease,
		arg.Name,
		arg.Artists,
		arg.MixName,
		arg.ReleaseDate,
		arg.ThumbnailUrl,
		arg.StmpdSlug,
		arg.SpotifyUrl,
		arg.AppleMusicUrl,
		arg.YoutubeUrl,
		arg.YoutubeMusicUrl,
		arg.DeezerUrl,
		arg.TidalUrl,
		arg.AmazonMusicUrl,
		arg.BeatportUrl,
		arg.BeatportReleaseID,
	)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Artists,
		&i.ThumbnailUrl,
		&i.SpotifyUrl,
		&i.AppleMusicUrl,
		&i.YoutubeUrl,
		&i.Lyrics,
		&i.IsUnreleased,
		&i.BeatportID,
		&i.MixName,
		&i.ReleaseDate,
		&i.ReleaseName,
		&i.Genre,
		&i.SubGenre,
		&i.Bpm,
		&i.MusicalKey,
		&i.LengthMs,
		&i.BeatportUpdated,
		&i.Source,
		&i.FirstSeenAt,
		&i.AnnouncedAt,
		&i.StmpdSyncedAt,
		&i.DeezerUrl,
		&i.TidalUrl,
		&i.AmazonMusicUrl,
		&i.YoutubeMusicUrl,
		&i.BeatportUrl,
		&i.BeatportReleaseID,
		&i.StmpdSlug,
		&i.MatchKey,
		&i.BaseKey,
		&i.ParentSongID,
		&i.IsInstrumental,
		&i.IsCollection,
		&i.BeatportSlug,
		&i.NormalizedName,
		&i.LrclibID,
		&i.LrclibCheckedAt,
		&i.LrclibMisses,
		&i.LockedFields,
		&i.SearchText,
	)
	return i, err
}

const markBeatportUpdated = `-- name: MarkBeatportUpdated :exec
UPDATE songs SET beatport_updated = TRUE WHERE id = $1
`

func (q *Queries) MarkBeatportUpdated(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markBeatportUpdated, id)
	return err
}

const markLrclibChecked = `-- name: MarkLrclibChecked :exec
UPDATE songs SET lrclib_checked_at = NOW() WHERE id = $1
`

// Stamps the attempt without spending one, for a row whose result was rejected for a
// reason that is not LRCLIB's fault.
func (q *Queries) MarkLrclibChecked(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markLrclibChecked, id)
	return err
}

const markLrclibMiss = `-- name: MarkLrclibMiss :exec
UPDATE songs SET lrclib_checked_at = NOW(), lrclib_misses = lrclib_misses + 1
WHERE id = $1
`

// LRCLIB answered and had nothing usable. Spends one of the row's four attempts.
func (q *Queries) MarkLrclibMiss(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markLrclibMiss, id)
	return err
}

const markSongAnnounced = `-- name: MarkSongAnnounced :exec
UPDATE songs SET announced_at = NOW() WHERE id = $1 AND announced_at IS NULL
`

func (q *Queries) MarkSongAnnounced(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markSongAnnounced, id)
	return err
}

const markSongInstrumentalFromLrclib = `-- name: MarkSongInstrumentalFromLrclib :execrows
UPDATE songs SET is_instrumental = TRUE, lrclib_id = $1,
                 lrclib_checked_at = NOW(), lrclib_misses = 0
WHERE id = $2 AND NOT is_instrumental
  AND NOT ('is_instrumental' = ANY(locked_fields))
`

type MarkSongInstrumentalFromLrclibParams struct {
	LrclibID pgtype.Int8 `json:"lrclibId"`
	ID       int64       `json:"id"`
}

// LRCLIB says this recording has no words. Migration 000012 added is_instrumental for
// exactly this: without a way to say so, an instrumental sits in the missing-lyrics
// backlog forever and the quiz can pick it and ask a player to recall words that do
// not exist. LRCLIB is the first source that can answer the question automatically.
func (q *Queries) MarkSongInstrumentalFromLrclib(ctx context.Context, arg MarkSongInstrumentalFromLrclibParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSongInstrumentalFromLrclib, arg.LrclibID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSongUnreleased = `-- name: MarkSongUnreleased :exec
UPDATE songs SET is_unreleased = TRUE, release_date = NULL WHERE id = $1
`

// For adding a track that has been played but not put out. The date must go with it:
// the unreleased_has_no_date constraint will not allow one without the other.
func (q *Queries) MarkSongUnreleased(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markSongUnreleased, id)
	return err
}

const mergeSongRows = `-- name: MergeSongRows :exec
WITH l AS (
    DELETE FROM songs d WHERE d.id = $2 RETURNING d.id, d.name, d.artists, d.thumbnail_url, d.spotify_url, d.apple_music_url, d.youtube_url, d.lyrics, d.is_unreleased, d.beatport_id, d.mix_name, d.release_date, d.release_name, d.genre, d.sub_genre, d.bpm, d.musical_key, d.length_ms, d.beatport_updated, d.source, d.first_seen_at, d.announced_at, d.stmpd_synced_at, d.deezer_url, d.tidal_url, d.amazon_music_url, d.youtube_music_url, d.beatport_url, d.beatport_release_id, d.stmpd_slug, d.match_key, d.base_key, d.parent_song_id, d.is_instrumental, d.is_collection, d.beatport_slug, d.normalized_name, d.lrclib_id, d.lrclib_checked_at, d.lrclib_misses, d.locked_fields, d.search_text
)
UPDATE songs w SET
    spotify_url     = COALESCE(w.spotify_url,     l.spotify_url),
    apple_music_url = COALESCE(w.apple_music_url, l.apple_music_url),
    youtube_url     = COALESCE(w.youtube_url,     l.youtube_url),
    thumbnail_url   = COALESCE(NULLIF(w.thumbnail_url, ''), l.thumbnail_url),
    lyrics          = COALESCE(w.lyrics,          l.lyrics),
    bpm             = COALESCE(w.bpm,             l.bpm),
    musical_key     = COALESCE(w.musical_key,     l.musical_key),
    length_ms       = COALESCE(w.length_ms,       l.length_ms),
    genre           = COALESCE(w.genre,           l.genre),
    sub_genre       = COALESCE(w.sub_genre,       l.sub_genre),
    mix_name        = COALESCE(w.mix_name,        l.mix_name),
    release_name    = COALESCE(w.release_name,    l.release_name),
    -- The columns below were added after this query was first written. Leaving them
    -- out silently discarded the loser's slug and its deezer/tidal/amazon links.
    -- beatport_id and stmpd_slug are handled by Release/AdoptSongIdentifiers:
    -- both are uniquely indexed and cannot be copied while the loser still holds them.
    youtube_music_url   = COALESCE(w.youtube_music_url,   l.youtube_music_url),
    deezer_url          = COALESCE(w.deezer_url,          l.deezer_url),
    tidal_url           = COALESCE(w.tidal_url,           l.tidal_url),
    amazon_music_url    = COALESCE(w.amazon_music_url,    l.amazon_music_url),
    beatport_url        = COALESCE(w.beatport_url,        l.beatport_url),
    beatport_release_id = COALESCE(w.beatport_release_id, l.beatport_release_id),
    -- beatport_slug travels with beatport_id, and leaving it behind is not cosmetic: a
    -- track page is /track/<slug>/<id>, so a winner that adopts the loser's id without
    -- its slug ends up with a Beatport button that 404s. It was omitted here because
    -- the two uniquely-indexed identifiers next to it need the release/adopt dance;
    -- this one has no unique index and can simply be copied. A dedupe run that folded
    -- 108 beatport rows into STMPD winners broke 99 buttons that way.
    beatport_slug       = COALESCE(w.beatport_slug,       l.beatport_slug),
    -- A real date always beats the 1970-01-01 placeholder, whichever row holds it.
    release_date    = CASE WHEN w.release_date = '1970-01-01' AND l.release_date <> '1970-01-01'
                           THEN l.release_date ELSE w.release_date END,
    announced_at    = LEAST(w.announced_at,       l.announced_at),
    first_seen_at   = LEAST(w.first_seen_at,      l.first_seen_at),
    stmpd_synced_at = COALESCE(w.stmpd_synced_at, l.stmpd_synced_at),
    beatport_updated = w.beatport_updated OR l.beatport_updated,
    -- The union, not the winner's set. A lock records that a person corrected that
    -- column by hand; dropping the loser's locks would hand its hand-corrected columns
    -- straight back to the next sync to overwrite.
    locked_fields = (SELECT COALESCE(array_agg(DISTINCT e), '{}')
                     FROM unnest(w.locked_fields || l.locked_fields) e)
FROM l
WHERE w.id = $1
`

type MergeSongRowsParams struct {
	WinnerID int64 `json:"winnerId"`
	LoserID  int64 `json:"loserId"`
}

// Fold `loser` into `winner`, keeping the first non-null of each field, and delete
// the loser. Used when a release_date correction would collide with the
// unique_release constraint: the collision means a twin row already holds that
// identity, so the two are the same song arriving from two sources.
//
// The delete is part of this statement rather than a DeleteSong call after it, and
// that is the whole point. unique_release is (name, artists, mix_name, release_date)
// NULLS NOT DISTINCT, and the COALESCEs below can hand the winner the very identity
// the loser still holds: a pair differing only in that one names "Extended Mix" and
// the other names no rendition ends with the winner adopting "Extended Mix" while the
// loser is still sitting in the index. That is a 23505, and it took the whole merge
// down after the release/adopt dance had already run --
//
//	Key (name, artists, mix_name, release_date)=(Waiting For Love, Brooks, Alida,
//	Extended Mix, 2019-07-26) already exists
//
// -- on a catalogue where exactly that pair is the commonest kind of duplicate,
// because beatport files nearly every plain release as an extended mix.
//
// Deleting inside the statement removes the conflicting row before the index check
// for the update runs, so the winner can take an identity the loser was holding.
// Every caller deleted the loser on the next line anyway; none may do so now.
func (q *Queries) MergeSongRows(ctx context.Context, arg MergeSongRowsParams) error {
	_, err := q.db.Exec(ctx, mergeSongRows, arg.WinnerID, arg.LoserID)
	return err
}

const releaseSongIdentifiers = `-- name: ReleaseSongIdentifiers :exec
UPDATE songs SET beatport_id = NULL, stmpd_slug = NULL WHERE id = $1
`

// Clear the uniquely-indexed identifiers from a row that is about to be merged away.
//
// beatport_id and stmpd_slug each carry a partial unique index, so copying them onto
// the surviving row while this one still holds them violates the index. The caller
// captured the values first and reassigns them with AdoptSongIdentifiers once this
// row no longer claims them.
func (q *Queries) ReleaseSongIdentifiers(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, releaseSongIdentifiers, id)
	return err
}

const repointChildren = `-- name: RepointChildren :execrows
UPDATE songs SET parent_song_id = $1
WHERE parent_song_id = $2
`

type RepointChildrenParams struct {
	NewParent pgtype.Int8 `json:"newParent"`
	OldParent pgtype.Int8 `json:"oldParent"`
}

// Move a merged-away row's remixes onto the row that survives.
func (q *Queries) RepointChildren(ctx context.Context, arg RepointChildrenParams) (int64, error) {
	result, err := q.db.Exec(ctx, repointChildren, arg.NewParent, arg.OldParent)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const searchSongsForAgent = `-- name: SearchSongsForAgent :many
SELECT id, name, artists, mix_name, release_date, is_unreleased, genre
FROM songs
WHERE NOT is_collection
  AND COALESCE(search_text,
               LOWER(artists || ' ' || name || ' ' || COALESCE(mix_name, '')))
        LIKE ALL ($1::text[])
ORDER BY (parent_song_id IS NOT NULL), release_date DESC
LIMIT 20
`

type SearchSongsForAgentRow struct {
	ID           int64       `json:"id"`
	Name         string      `json:"name"`
	Artists      string      `json:"artists"`
	MixName      pgtype.Text `json:"mixName"`
	ReleaseDate  pgtype.Text `json:"releaseDate"`
	IsUnreleased bool        `json:"isUnreleased"`
	Genre        pgtype.Text `json:"genre"`
}

// Backs the AI persona feature's "search_songs" tool (stmpdbot/ai). Same term
// matching as GetSongsLike below, but also returns is_unreleased and genre so
// the model can answer "favourite unreleased AREA21 track"-shaped questions
// from the rows themselves instead of typing "unreleased" into the search
// terms (which would never match search_text and return nothing) or, worse,
// inventing a track name that was never in the catalogue.
func (q *Queries) SearchSongsForAgent(ctx context.Context, dollar_1 []string) ([]SearchSongsForAgentRow, error) {
	rows, err := q.db.Query(ctx, searchSongsForAgent, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchSongsForAgentRow
	for rows.Next() {
		var i SearchSongsForAgentRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Artists,
			&i.MixName,
			&i.ReleaseDate,
			&i.IsUnreleased,
			&i.Genre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBeatportSlug = `-- name: SetBeatportSlug :execrows
UPDATE songs SET beatport_slug = $2
WHERE id = $1 AND beatport_slug IS DISTINCT FROM $2
`

type SetBeatportSlugParams struct {
	ID           int64       `json:"id"`
	BeatportSlug pgtype.Text `json:"beatportSlug"`
}

// Fills the slug that turns a stored beatport_id into a URL that resolves.
func (q *Queries) SetBeatportSlug(ctx context.Context, arg SetBeatportSlugParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBeatportSlug, arg.ID, arg.BeatportSlug)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSongArtwork = `-- name: SetSongArtwork :execrows
UPDATE songs SET thumbnail_url = $1
WHERE id = $2 AND coalesce(thumbnail_url, '') = ''
  AND NOT ('thumbnail_url' = ANY(locked_fields))
`

type SetSongArtworkParams struct {
	ThumbnailUrl pgtype.Text `json:"thumbnailUrl"`
	ID           int64       `json:"id"`
}

func (q *Queries) SetSongArtwork(ctx context.Context, arg SetSongArtworkParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSongArtwork, arg.ThumbnailUrl, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSongCollection = `-- name: SetSongCollection :execrows
UPDATE songs SET is_collection = $2
WHERE id = $1 AND is_collection IS DISTINCT FROM $2
  AND NOT ('is_collection' = ANY(locked_fields))
`

type SetSongCollectionParams struct {
	ID           int64 `json:"id"`
	IsCollection bool  `json:"isCollection"`
}

func (q *Queries) SetSongCollection(ctx context.Context, arg SetSongCollectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSongCollection, arg.ID, arg.IsCollection)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSongInstrumental = `-- name: SetSongInstrumental :execrows
UPDATE songs SET is_instrumental = $2
WHERE id = $1 AND is_instrumental IS DISTINCT FROM $2
  AND NOT ('is_instrumental' = ANY(locked_fields))
`

type SetSongInstrumentalParams struct {
	ID             int64 `json:"id"`
	IsInstrumental bool  `json:"isInstrumental"`
}

func (q *Queries) SetSongInstrumental(ctx context.Context, arg SetSongInstrumentalParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSongInstrumental, arg.ID, arg.IsInstrumental)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSongKeys = `-- name: SetSongKeys :execrows
UPDATE songs SET match_key = $2, base_key = $3, search_text = $4
WHERE id = $1 AND (match_key IS DISTINCT FROM $2
                OR base_key IS DISTINCT FROM $3
                OR search_text IS DISTINCT FROM $4)
`

type SetSongKeysParams struct {
	ID         int64       `json:"id"`
	MatchKey   pgtype.Text `json:"matchKey"`
	BaseKey    pgtype.Text `json:"baseKey"`
	SearchText pgtype.Text `json:"searchText"`
}

// search_text rides along with the match keys rather than getting a writer of its own:
// all three are derived from name + artists by the same pass, and a path that could
// update one without the others is a path that leaves a renamed song unfindable.
//
// Deliberately not guarded by locked_fields. These are pure derivations, not values a
// human would ever want to pin; locking them would mean a hand-corrected title never
// became searchable under its new spelling.
func (q *Queries) SetSongKeys(ctx context.Context, arg SetSongKeysParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSongKeys,
		arg.ID,
		arg.MatchKey,
		arg.BaseKey,
		arg.SearchText,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSongLyrics = `-- name: SetSongLyrics :execrows
UPDATE songs SET lyrics = $1, lrclib_id = $2,
                 lrclib_checked_at = NOW(), lrclib_misses = 0
WHERE id = $3 AND lyrics IS NULL
  AND NOT ('lyrics' = ANY(locked_fields))
`

type SetSongLyricsParams struct {
	Lyrics   pgtype.Text `json:"lyrics"`
	LrclibID pgtype.Int8 `json:"lrclibId"`
	ID       int64       `json:"id"`
}

// Guarded on lyrics IS NULL so a backfill can never overwrite words entered by hand.
// Those exist nowhere else, which is why dedupe-songs makes them a winner-selection
// tiebreaker, and a fill that clobbered them would be unrecoverable.
func (q *Queries) SetSongLyrics(ctx context.Context, arg SetSongLyricsParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSongLyrics, arg.Lyrics, arg.LrclibID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSongNormalizedName = `-- name: SetSongNormalizedName :execrows
UPDATE songs SET normalized_name = $1
WHERE id = $2 AND normalized_name IS DISTINCT FROM $1
  AND NOT ('normalized_name' = ANY(locked_fields))
`

type SetSongNormalizedNameParams struct {
	NormalizedName pgtype.Text `json:"normalizedName"`
	ID             int64       `json:"id"`
}

// The answerable form of the title, derived in Go by utils/title.go.
func (q *Queries) SetSongNormalizedName(ctx context.Context, arg SetSongNormalizedNameParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSongNormalizedName, arg.NormalizedName, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSongParent = `-- name: SetSongParent :execrows
UPDATE songs SET parent_song_id = $1
WHERE id = $2 AND parent_song_id IS DISTINCT FROM $1
  AND NOT ('parent_song_id' = ANY(locked_fields))
`

type SetSongParentParams struct {
	ParentSongID pgtype.Int8 `json:"parentSongId"`
	ID           int64       `json:"id"`
}

func (q *Queries) SetSongParent(ctx context.Context, arg SetSongParentParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSongParent, arg.ParentSongID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSongReleaseDate = `-- name: SetSongReleaseDate :execrows
UPDATE songs SET release_date = $2
WHERE id = $1 AND release_date IS DISTINCT FROM $2
  AND NOT ('release_date' = ANY(locked_fields))
`

type SetSongReleaseDateParams struct {
	ID          int64       `json:"id"`
	ReleaseDate pgtype.Text `json:"releaseDate"`
}

func (q *Queries) SetSongReleaseDate(ctx context.Context, arg SetSongReleaseDateParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSongReleaseDate, arg.ID, arg.ReleaseDate)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSongTitle = `-- name: SetSongTitle :execrows
UPDATE songs SET
    name = CASE WHEN 'name' = ANY(locked_fields) THEN name ELSE $1 END,
    mix_name = CASE WHEN 'mix_name' = ANY(locked_fields) THEN mix_name ELSE $2 END,
    normalized_name = CASE WHEN 'normalized_name' = ANY(locked_fields) THEN normalized_name
                           ELSE $3 END
WHERE id = $4
  AND ((NOT ('name' = ANY(locked_fields)) AND name IS DISTINCT FROM $1)
    OR (NOT ('mix_name' = ANY(locked_fields)) AND mix_name IS DISTINCT FROM $2)
    OR (NOT ('normalized_name' = ANY(locked_fields))
        AND normalized_name IS DISTINCT FROM $3))
`

type SetSongTitleParams struct {
	Name           string      `json:"name"`
	MixName        pgtype.Text `json:"mixName"`
	NormalizedName pgtype.Text `json:"normalizedName"`
	ID             int64       `json:"id"`
}

// normalized_name is written here too, and has to be: this query is how rekey-songs
// rewrites a name, so leaving it out would guarantee the derived column is stale on
// exactly the rows that needed correcting.
func (q *Queries) SetSongTitle(ctx context.Context, arg SetSongTitleParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSongTitle,
		arg.Name,
		arg.MixName,
		arg.NormalizedName,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSongYoutubeURL = `-- name: SetSongYoutubeURL :execrows
UPDATE songs SET youtube_url = $1
WHERE id = $2 AND youtube_url IS DISTINCT FROM $1
  AND NOT ('youtube_url' = ANY(locked_fields))
`

type SetSongYoutubeURLParams struct {
	YoutubeUrl pgtype.Text `json:"youtubeUrl"`
	ID         int64       `json:"id"`
}

func (q *Queries) SetSongYoutubeURL(ctx context.Context, arg SetSongYoutubeURLParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSongYoutubeURL, arg.YoutubeUrl, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSongWithBeatportData = `-- name: UpdateSongWithBeatportData :execrows
UPDATE songs SET
    name          = CASE WHEN 'name' = ANY(locked_fields) THEN name ELSE $1 END,
    artists       = CASE WHEN 'artists' = ANY(locked_fields) THEN artists ELSE $2 END,
    thumbnail_url = CASE WHEN 'thumbnail_url' = ANY(locked_fields) THEN thumbnail_url
                         ELSE COALESCE($3, thumbnail_url) END,
    beatport_id   = $4,
    beatport_slug = COALESCE($5, beatport_slug),
    mix_name      = CASE WHEN 'mix_name' = ANY(locked_fields) THEN mix_name ELSE $6 END,
    -- LEAST ignores NULLs, so this reads as "the earlier of the two, or whichever one
    -- exists". The NULLIFs keep the placeholders out of that comparison: '1970-01-01'
    -- is the old importer's "no date", and it would win every race it entered.
    release_date  = CASE WHEN 'release_date' = ANY(locked_fields) THEN release_date
                         ELSE COALESCE(LEAST(NULLIF(release_date, '1970-01-01'),
                                             NULLIF($7::text, '')),
                                       release_date) END,
    release_name  = CASE WHEN 'release_name' = ANY(locked_fields) THEN release_name ELSE $8 END,
    genre         = CASE WHEN 'genre' = ANY(locked_fields) THEN genre ELSE $9 END,
    sub_genre     = CASE WHEN 'sub_genre' = ANY(locked_fields) THEN sub_genre ELSE $10 END,
    bpm           = CASE WHEN 'bpm' = ANY(locked_fields) THEN bpm ELSE $11 END,
    musical_key   = CASE WHEN 'musical_key' = ANY(locked_fields) THEN musical_key ELSE $12 END,
    length_ms     = $13,
    beatport_updated = TRUE
WHERE id = $14
  AND (
       (NOT ('name' = ANY(locked_fields))          AND name          IS DISTINCT FROM $1)
    OR (NOT ('artists' = ANY(locked_fields))       AND artists       IS DISTINCT FROM $2)
    OR (NOT ('thumbnail_url' = ANY(locked_fields)) AND thumbnail_url IS DISTINCT FROM COALESCE($3, thumbnail_url))
    OR beatport_id   IS DISTINCT FROM $4
    OR beatport_slug IS DISTINCT FROM COALESCE($5, beatport_slug)
    OR (NOT ('mix_name' = ANY(locked_fields))      AND mix_name      IS DISTINCT FROM $6)
    OR (NOT ('release_date' = ANY(locked_fields))
        AND release_date IS DISTINCT FROM COALESCE(LEAST(NULLIF(release_date, '1970-01-01'),
                                                         NULLIF($7::text, '')),
                                                   release_date))
    OR (NOT ('release_name' = ANY(locked_fields))  AND release_name  IS DISTINCT FROM $8)
    OR (NOT ('genre' = ANY(locked_fields))         AND genre         IS DISTINCT FROM $9)
    OR (NOT ('sub_genre' = ANY(locked_fields))     AND sub_genre     IS DISTINCT FROM $10)
    OR (NOT ('bpm' = ANY(locked_fields))           AND bpm           IS DISTINCT FROM $11)
    OR (NOT ('musical_key' = ANY(locked_fields))   AND musical_key   IS DISTINCT FROM $12)
    OR length_ms     IS DISTINCT FROM $13
    OR beatport_updated IS DISTINCT FROM TRUE
  )
`

type UpdateSongWithBeatportDataParams struct {
	Name         string      `json:"name"`
	Artists      string      `json:"artists"`
	ThumbnailUrl pgtype.Text `json:"thumbnailUrl"`
	BeatportID   pgtype.Int4 `json:"beatportId"`
	BeatportSlug pgtype.Text `json:"beatportSlug"`
	MixName      pgtype.Text `json:"mixName"`
	ReleaseDate  pgtype.Text `json:"releaseDate"`
	ReleaseName  pgtype.Text `json:"releaseName"`
	Genre        pgtype.Text `json:"genre"`
	SubGenre     pgtype.Text `json:"subGenre"`
	Bpm          pgtype.Int4 `json:"bpm"`
	MusicalKey   pgtype.Text `json:"musicalKey"`
	LengthMs     pgtype.Int4 `json:"lengthMs"`
	ID           int64       `json:"id"`
}

// :execrows plus the IS DISTINCT FROM guard below make this a no-op when the row
// already holds this data. Without it every cycle rewrote the same ~73 rows and
// reported updated=73 forever, which hid whether anything had actually changed.
// thumbnail_url is COALESCEd rather than assigned: a beatport track with no square
// artwork arrives as NULL and must not erase artwork another source already found.
//
// Every editable column is wrapped in a locked_fields test, and the same test is
// repeated in the WHERE. Both halves are needed. Guarding only the SET list would leave
// the WHERE matching forever: the other assignments still fire, :execrows keeps
// returning 1 every cycle, and the write churn the IS DISTINCT FROM guards were added
// to kill comes straight back.
//
// beatport_updated is deliberately unguarded -- it is the fetcher's own "already
// enriched" sentinel, and locking it would stall the fetcher rather than protect
// anything a person typed.
//
// release_date is the one column here that may only ever move *earlier*. What beatport
// reports is publish_date -- when the track appeared on beatport, not when the record
// came out -- and the two diverge whenever a label re-delivers its back catalogue: the
// 2012 Martin Garrix remix of "Midnight Sun 2.0" carries beatport track id 27274826 and
// a publish date of 2021-09-06, and so did four rows in this table until someone in the
// server pointed out that the bot was announcing a 2012 record as a 2021 one. Taking the
// earlier of the two dates keeps a re-delivery from overwriting a date another source
// got right, and still lets beatport fill in a date the row does not have. Correcting a
// date that is wrongly *early* is a person's job through the dashboard, which locks it.
func (q *Queries) UpdateSongWithBeatportData(ctx context.Context, arg UpdateSongWithBeatportDataParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSongWithBeatportData,
		arg.Name,
		arg.Artists,
		arg.ThumbnailUrl,
		arg.BeatportID,
		arg.BeatportSlug,
		arg.MixName,
		arg.ReleaseDate,
		arg.ReleaseName,
		arg.Genre,
		arg.SubGenre,
		arg.Bpm,
		arg.MusicalKey,
		arg.LengthMs,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSongWithStmpdLinks = `-- name: UpdateSongWithStmpdLinks :execrows
UPDATE songs SET
    spotify_url     = COALESCE($1,     spotify_url),
    apple_music_url = COALESCE($2, apple_music_url),
    youtube_url     = COALESCE($3,     youtube_url),
    thumbnail_url   = CASE WHEN thumbnail_url IS NULL OR thumbnail_url = ''
                           THEN $4 ELSE thumbnail_url END,
    stmpd_synced_at = NOW()
WHERE id = $5
  AND (
       spotify_url     IS DISTINCT FROM COALESCE($1,     spotify_url)
    OR apple_music_url IS DISTINCT FROM COALESCE($2, apple_music_url)
    OR youtube_url     IS DISTINCT FROM COALESCE($3,     youtube_url)
    -- Only a reason to write when there is actually a thumbnail to write. Testing
    -- emptiness alone would match forever on a row neither side has artwork for,
    -- re-stamping it every cycle and reintroducing the churn this guard removes.
    --
    -- The cast is required, not cosmetic: IS NOT NULL accepts any type, so this is
    -- the one place the parameter appears without a type to infer from, and Postgres
    -- rejects the whole statement with 42P08 at execution time.
    OR (COALESCE(thumbnail_url, '') = '' AND $4::text IS NOT NULL)
    OR stmpd_synced_at IS NULL
  )
`

type UpdateSongWithStmpdLinksParams struct {
	SpotifyUrl    pgtype.Text `json:"spotifyUrl"`
	AppleMusicUrl pgtype.Text `json:"appleMusicUrl"`
	YoutubeUrl    pgtype.Text `json:"youtubeUrl"`
	ThumbnailUrl  pgtype.Text `json:"thumbnailUrl"`
	ID            int64       `json:"id"`
}

// This no longer touches beatport_updated. That flag is the beatport fetcher's own
// "already enriched, skip" sentinel; setting it here made the STMPD backfill skip
// every row beatport had ever touched, which is why 497 beatport rows had no links.
// stmpd_synced_at is this fetcher's separate record of having visited the row.
func (q *Queries) UpdateSongWithStmpdLinks(ctx context.Context, arg UpdateSongWithStmpdLinksParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSongWithStmpdLinks,
		arg.SpotifyUrl,
		arg.AppleMusicUrl,
		arg.YoutubeUrl,
		arg.ThumbnailUrl,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSongWithStmpdRelease = `-- name: UpdateSongWithStmpdRelease :execrows
UPDATE songs SET
    stmpd_slug          = COALESCE($1,          stmpd_slug),
    release_date        = CASE WHEN 'release_date' = ANY(locked_fields) THEN release_date
                               ELSE COALESCE($2, release_date) END,
    -- The catalogue is the authority for what a release is called and which
    -- rendition it is, so both are taken from it rather than merged with whatever
    -- the row happened to hold. This is what keeps the shape uniform: the name is
    -- the song's name and the rendition lives in mix_name, never smuggled into the
    -- title for some rows and not others.
    name                = CASE WHEN 'name' = ANY(locked_fields) THEN name
                               ELSE COALESCE($3, name) END,
    mix_name            = CASE WHEN 'mix_name' = ANY(locked_fields) THEN mix_name
                               ELSE $4 END,
    -- normalized_name is derived from name in Go, so a name the catalogue rewrote
    -- here invalidates it. Cleared rather than recomputed: SQL cannot derive it, and
    -- NULL falls back to computing on read, whereas a leftover value would be
    -- confidently wrong. The handler re-reads the row and refills this immediately.
    normalized_name     = CASE WHEN name IS DISTINCT FROM COALESCE($3, name)
                               THEN NULL ELSE normalized_name END,
    spotify_url = CASE WHEN 'spotify_url' = ANY(locked_fields) THEN spotify_url
                               ELSE COALESCE($5, spotify_url) END,
    apple_music_url = CASE WHEN 'apple_music_url' = ANY(locked_fields) THEN apple_music_url
                               ELSE COALESCE($6, apple_music_url) END,
    youtube_url = CASE WHEN 'youtube_url' = ANY(locked_fields) THEN youtube_url
                               ELSE COALESCE($7, youtube_url) END,
    youtube_music_url = CASE WHEN 'youtube_music_url' = ANY(locked_fields) THEN youtube_music_url
                               ELSE COALESCE($8, youtube_music_url) END,
    deezer_url = CASE WHEN 'deezer_url' = ANY(locked_fields) THEN deezer_url
                               ELSE COALESCE($9, deezer_url) END,
    tidal_url = CASE WHEN 'tidal_url' = ANY(locked_fields) THEN tidal_url
                               ELSE COALESCE($10, tidal_url) END,
    amazon_music_url = CASE WHEN 'amazon_music_url' = ANY(locked_fields) THEN amazon_music_url
                               ELSE COALESCE($11, amazon_music_url) END,
    beatport_url = CASE WHEN 'beatport_url' = ANY(locked_fields) THEN beatport_url
                               ELSE COALESCE($12, beatport_url) END,
    beatport_release_id = COALESCE($13, beatport_release_id),
    thumbnail_url       = CASE WHEN COALESCE(thumbnail_url, '') = ''
                                     AND NOT ('thumbnail_url' = ANY(locked_fields))
                               THEN $14 ELSE thumbnail_url END,
    -- A song someone added because they heard it played, which has now actually
    -- come out. Clearing announced_at re-arms the announcement: the row is old, but
    -- the release is news, and this is the one case where re-announcing is right.
    --
    -- The ::text casts are load-bearing. IS NOT NULL accepts any type, so these are
    -- the only places the parameter appears without a type to infer from, and
    -- Postgres rejects the whole statement with 42P08 at execution time.
    is_unreleased = CASE WHEN $2::text IS NOT NULL
                              AND NOT ('release_date' = ANY(locked_fields))
                              AND NOT ('is_unreleased' = ANY(locked_fields))
                         THEN FALSE ELSE is_unreleased END,
    announced_at  = CASE WHEN is_unreleased AND $2::text IS NOT NULL
                              AND NOT ('release_date' = ANY(locked_fields))
                         THEN NULL ELSE announced_at END,
    stmpd_synced_at     = NOW()
WHERE id = $15
  AND (
       (is_unreleased AND $2::text IS NOT NULL
        AND NOT ('release_date' = ANY(locked_fields)))
    OR stmpd_slug          IS DISTINCT FROM COALESCE($1,          stmpd_slug)
    OR (NOT ('release_date' = ANY(locked_fields))
        AND release_date IS DISTINCT FROM COALESCE($2, release_date))
    OR (NOT ('name' = ANY(locked_fields))
        AND name IS DISTINCT FROM COALESCE($3, name))
    OR (NOT ('mix_name' = ANY(locked_fields))
        AND mix_name IS DISTINCT FROM $4)
    OR (NOT ('spotify_url' = ANY(locked_fields))
        AND spotify_url IS DISTINCT FROM COALESCE($5, spotify_url))
    OR (NOT ('apple_music_url' = ANY(locked_fields))
        AND apple_music_url IS DISTINCT FROM COALESCE($6, apple_music_url))
    OR (NOT ('youtube_url' = ANY(locked_fields))
        AND youtube_url IS DISTINCT FROM COALESCE($7, youtube_url))
    OR (NOT ('youtube_music_url' = ANY(locked_fields))
        AND youtube_music_url IS DISTINCT FROM COALESCE($8, youtube_music_url))
    OR (NOT ('deezer_url' = ANY(locked_fields))
        AND deezer_url IS DISTINCT FROM COALESCE($9, deezer_url))
    OR (NOT ('tidal_url' = ANY(locked_fields))
        AND tidal_url IS DISTINCT FROM COALESCE($10, tidal_url))
    OR (NOT ('amazon_music_url' = ANY(locked_fields))
        AND amazon_music_url IS DISTINCT FROM COALESCE($11, amazon_music_url))
    OR (NOT ('beatport_url' = ANY(locked_fields))
        AND beatport_url IS DISTINCT FROM COALESCE($12, beatport_url))
    OR beatport_release_id IS DISTINCT FROM COALESCE($13, beatport_release_id)
    -- Cast for the same reason as in UpdateSongWithStmpdLinks: IS NOT NULL leaves
    -- the parameter's type undetermined and Postgres raises 42P08.
    OR (COALESCE(thumbnail_url, '') = '' AND $14::text IS NOT NULL
        AND NOT ('thumbnail_url' = ANY(locked_fields)))
    OR stmpd_synced_at IS NULL
  )
`

type UpdateSongWithStmpdReleaseParams struct {
	StmpdSlug         pgtype.Text `json:"stmpdSlug"`
	ReleaseDate       pgtype.Text `json:"releaseDate"`
	Title             pgtype.Text `json:"title"`
	MixName           pgtype.Text `json:"mixName"`
	SpotifyUrl        pgtype.Text `json:"spotifyUrl"`
	AppleMusicUrl     pgtype.Text `json:"appleMusicUrl"`
	YoutubeUrl        pgtype.Text `json:"youtubeUrl"`
	YoutubeMusicUrl   pgtype.Text `json:"youtubeMusicUrl"`
	DeezerUrl         pgtype.Text `json:"deezerUrl"`
	TidalUrl          pgtype.Text `json:"tidalUrl"`
	AmazonMusicUrl    pgtype.Text `json:"amazonMusicUrl"`
	BeatportUrl       pgtype.Text `json:"beatportUrl"`
	BeatportReleaseID pgtype.Int4 `json:"beatportReleaseId"`
	ThumbnailUrl      pgtype.Text `json:"thumbnailUrl"`
	ID                int64       `json:"id"`
}

// The full-fidelity counterpart to UpdateSongWithStmpdLinks: everything the STMPD
// dataset knows about a release, applied to a row that already exists.
//
// release_date is COALESCEd rather than left alone because the dataset carries the
// exact date and many stored rows carry a "<year>-01-01" placeholder. Correcting it
// is safe now only because announcement is gated on songs.announced_at, which every
// pre-existing row already has stamped -- without that watermark this UPDATE would
// make the back catalogue look new.
//
// Every column a person can correct is wrapped in a locked_fields test, and the same
// test is mirrored in the WHERE. Both halves are needed: guarding only the SET list
// leaves the WHERE matching forever, so :execrows reports a write every cycle and the
// churn the IS DISTINCT FROM guards exist to kill comes straight back.
//
// The re-arm pair below additionally requires release_date to be unlocked. Without that
// a row whose date someone set by hand would have its announcement re-armed on the next
// sync and be posted to every server a second time.
//
// thumbnail_url is only ever filled in, never overwritten: roughly 800 of the 1015
// releases have no artwork in the dataset, and an empty value there means "unknown",
// not "this release has none".
func (q *Queries) UpdateSongWithStmpdRelease(ctx context.Context, arg UpdateSongWithStmpdReleaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSongWithStmpdRelease,
		arg.StmpdSlug,
		arg.ReleaseDate,
		arg.Title,
		arg.MixName,
		arg.SpotifyUrl,
		arg.AppleMusicUrl,
		arg.YoutubeUrl,
		arg.YoutubeMusicUrl,
		arg.DeezerUrl,
		arg.TidalUrl,
		arg.AmazonMusicUrl,
		arg.BeatportUrl,
		arg.BeatportReleaseID,
		arg.ThumbnailUrl,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
