package ai

import _ "embed"

// SOUL.md is the fixed identity/values/style contract: grounding rules (use
// the tools, never invent a fact), anti-sycophancy, the refusal to rate or
// rank the catalogue, and the em-dash ban. Hand-written, not data-derived --
// persona.md next to it is regenerated by scripts/analyze-fandom-voice, so a
// rule that has to survive the next regeneration belongs here.
//
//go:embed SOUL.md
var soul string

// persona.md is the static "voice guide" distilled offline from a random
// sample of this server's own message history by
// scripts/analyze-fandom-voice. It is folded into the system prompt once at
// startup rather than re-derived per message, so the running bot never pays
// an LLM call for tone -- only for the actual conversation.
//
//go:embed persona.md
var persona string

// SystemPrompt is the first message of every conversation: identity and
// grounding rules, then the sampled voice guide.
func SystemPrompt() string {
	return soul + "\n\n---\n\n" + persona
}
